### ISSUE TITLE
clean-up issue with conditional compile

### ISSUE THREAD

**Issue by WeihanLi** [codecadwallader/codemaid#892] opened 2021-12-20 02:57 UTC
### Environment
- Visual Studio version: VS 2022 Enterprise
- CodeMaid version: 12.0
- Code language: C#

### Description

When there's conditional compile for example `#if DEBUG`, sometimes the clean-up would break the original structure.

### Current behavior

before clean-up:

``` c#
#if DEBUG
public
#else
internal

static void MainTest(){}
#endif
```

After cleanup:

``` c#
#if DEBUG
public static void MainTest(){}
```

### Expected behavior

The structure should be the same as before clean-up.

**Comment by codecadwallader** [comment] 2021-12-21 15:38
Thanks for reporting the issue.  I believe this may be a duplicate of #879

**Closed as completed by codecadwallader** 2021-12-21 15:38 UTC
Labels: duplicate
