### ISSUE TITLE
CodeMaid Spade: Visual Basic comments are not displayed

### ISSUE THREAD

**Issue by aeab13** [codecadwallader/codemaid#326] opened 2016-08-16 14:58 UTC
### Environment
- Visual Studio version: 2015 Community
- CodeMaid version: 10.1
- Code language: VB .NET
### Description

Documentation comments are not displayed in CodeMaid Spade using VB .NET but they work using C#. Is this an issue?
### Steps to recreate
1. Create an example method with documentation comments.
2. Check CodeMaid Spade. 
   ![2016-08-16 16_56_13-consoleapplication5 - microsoft visual studio](https://cloud.githubusercontent.com/assets/16917468/17703556/6b1cf320-63d2-11e6-8729-bd76a9d06c82.png)
   ![2016-08-16 16_56_27-consoleapplication1 - microsoft visual studio](https://cloud.githubusercontent.com/assets/16917468/17703557/6b3d2208-63d2-11e6-97a8-641f1905837f.png)
### Current behavior

Comments are not displayed.
### Expected behavior

Comments should be displayed.

**Comment by codecadwallader** [comment] 2016-08-18 00:52
Thanks for reporting the issue, I have reproduced it.  I found a minor discrepancy in how VB and C# report the XML hierarchy that was causing us not to present the comment in the case of VB.  There was a very simple fix for it, which I've committed and will be available in our [CI channel](http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/) in a few moments (10.1.100 or higher) if you would like to test it out.  This will be a part of the next minor release as well.

Thanks again!

**Comment by aeab13** [comment] 2016-08-18 07:42
Now it is working! Thanks!
![2016-08-18 09_41_13-consoleapplication5 - microsoft visual studio](https://cloud.githubusercontent.com/assets/16917468/17765737/07775188-6528-11e6-85c0-ca62a490d51f.png)
![Uploading 2016-08-18 09_41_24-ConsoleApplication6 - Microsoft Visual Studio.png…]()

**Comment by aeab13** [comment] 2016-08-18 07:42
Now it is working! Thanks for fixing it!
![2016-08-18 09_41_13-consoleapplication5 - microsoft visual studio](https://cloud.githubusercontent.com/assets/16917468/17765756/1d1e577a-6528-11e6-909b-52e92d10bf05.png)
![2016-08-18 09_41_24-consoleapplication6 - microsoft visual studio](https://cloud.githubusercontent.com/assets/16917468/17765757/1d23197c-6528-11e6-98c9-c12321d0dadd.png)

**Comment by codecadwallader** [comment] 2016-08-18 12:01
Woot, thanks for confirming. :)

**Comment by codecadwallader** [comment] 2016-08-19 16:05
Let's leave this open until it's out in an official release, that makes it a little easier for other users to discover.

**Comment by aeab13** [comment] 2016-08-19 18:58
Oh, oke! Sorry, my bad!

**Comment by codecadwallader** [comment] 2016-08-19 19:06
All good :)

**Comment by aeab13** [comment] 2016-09-07 14:17
I've noticed that sometimes the problem persists. I add here a screenshot but I'm not sure about how it can be reproduced.
![microsoft visual studio](https://cloud.githubusercontent.com/assets/16917468/18315198/6a63195a-7516-11e6-8697-c0734e67dab7.png)

**Comment by codecadwallader** [comment] 2016-09-07 14:22
It looks like you have some unsaved changes.  The code model is built on load (or refresh or save) but will not live update so that may be the cause?  A live updating model is something we'd love to have in the future, but will require a large rewrite to Roslyn APIs.

**Comment by aeab13** [comment] 2016-09-07 14:25
Nope, I'm testing it againt but everything is saved correctly, it's really weird. I've closed the project and I've reopened it but the problem persists.

**Comment by aeab13** [comment] 2016-09-12 08:42
Note: I've noticed  that in the same class, in some methods the description is displayed but in the other methods the comments are not displayed. I'm not sure of what is working wrong.

**Comment by codecadwallader** [comment] 2016-09-12 12:36
That is strange.  Can you provide the file?  Perhaps there is something different in the formatting that is causing it not to get recognized.

**Comment by aeab13** [comment] 2016-09-16 15:43
Yeah! And sorry for the late answer.
[CalculosController.zip](https://github.com/codecadwallader/codemaid/files/477093/CalculosController.zip)

**Comment by aeab13** [comment] 2016-09-17 19:06
I'm debugging it and it seems that it is crashing when there are multiple documentation tags. 
Look at DocCommentToStringConverter class
                `var xElement = XElement.Parse(str);`

For example:
This is working:
```
    ''' <summary>
    ''' This is a test
    ''' </summary>
 ```
This not:
```
    ''' <summary>
    ''' Test
    ''' </summary>
    ''' <param name="price">Price test</param>
```
I'm trying to resolve it.

**Comment by codecadwallader** [comment] 2016-09-17 20:47
I wonder if it's because they're not well-formatted XML (i.e. there is no
single root element) - even though that is the correct convention for
documentation comments.  I remembered making this specific tweak to support
VB since it does not auto-create a single root element, which the C# API
did:
https://github.com/codecadwallader/codemaid/commit/00460f392440a5b29d8b19014235c04a889400fc

Perhaps another fix would be to insert and append XML to the front and end
of the string before sending it to XElement.Parse?  We'd have to make sure
that didn't interfere with the other scenarios (e.g. single doc tag or C#).

**Comment by codecadwallader** [comment] 2016-09-17 20:48
Ha!  Just saw your edits and that's exactly what I was thinking too. :)  Do you mind making that into a pull request?

**Comment by aeab13** [comment] 2016-09-17 21:10
Yeah, sure!

**Closed** 2016-12-08 14:33 UTC
Labels: bug, feature: digging, reproduced
