### ISSUE TITLE
On cleanup (project, solution, selected) Javascript does not run "format document" part 2

### ISSUE THREAD

**Issue by jolsa** [codecadwallader/codemaid#156] opened 2015-09-21 13:46 UTC
I saw you closed this and I replied, but you may not see comments on closed tickets, so I'm entering a new one... Sorry if that's not the proper protocol.

I found that feature (Cleanup selected code and choosing file types), but it doesn't solve my problem. We have some sloppy code files (many, many of them) with inconsistent formatting and we were looking for a tool that could open each file and execute the "format document" command on each file without writing our own. Code maid does that, but for some reason not on Javascript files. It is opening them and doing all of the cool extra things "cleanup" is configured to do, except "format document". It's formatting the C# files, HTML, and XML files as well as the other nice features Code Maid offers, but it's not formatting the Javascript. However, if I open a single file and execute "Cleanup" it does reformat the document.

**Comment by jolsa** [comment] 2015-09-21 15:38
I just rebooted (I also disabled and re-enabled Code Maid) and it's working now.  I'm pretty sure I'm not crazy... I tried this several times on Friday before submitting the bug.

**Comment by jolsa** [comment] 2015-09-21 15:40
Spoke too soon!  Sorry.  The file where it worked was one I had done as a single-file operation... not the whole project or folder.

**Comment by jolsa** [comment] 2015-09-21 15:46
Further investigation shows that it is working on some, but not all of the Javascript files when I right click the project and select "Cleanup Selected Code".  There are 186 affected files, so I can't give you an exact number without examining each.  I thought maybe there was something screwy with the files that didn't format, but I ran cleanup on them individually and they worked.

**Comment by codecadwallader** [comment] 2015-09-22 12:22
Continuation of #155 

We could have kept the existing issue going (I do see comments on closed items), but not a problem.

Is it always the same files that are not getting cleaned up, or does it seem to be random (i.e. File A won't clean up one time, but will clean up the next)?  If it's always the same files, is there anything that can be related about them (e.g. small files clean up fine but large files do not)?

**Comment by jolsa** [comment] 2015-09-22 15:48
I haven't determined a pattern.  My project has 194 Javascript files.  I started going through them one at a time (I didn't get all the way through them).  I found a subfolder that had 3 .js files where 1 out of 3 were reformatted.  I selected the folder and executed "Cleanup Selected Code", and it fixed on, but not the other.  I can't remember whether I tried it one more time... I had to move on to other things.  I do have some time right now, so I'm starting over.  I'll see if I can detect a pattern.

**Comment by jolsa** [comment] 2015-09-22 16:02
I started over.  I have a folder with 10 .js files and none of them were reformatted (one of them didn't even get the other Code Maid activity), so I selected the folder and ran it again.  No change.

I opened all 10 files and ran cleanup on the folder and they were all fixed.

Our Javascript files have more formatting consistency problems than our C#.  I wonder if some of the C# files are not getting formatted, but they're close enough already where I don't notice?  Code Maid is inserting blank lines (or removing them) as configured, so it's processing the files... just not reformatting all of them.  Could it be a timing issue?  Maybe because of the size of the project (over 1100 files to process), it's executing the reformat, but saving and closing the file before it's complete?

Just a suggestion.

**Comment by jolsa** [comment] 2015-09-22 16:10
Just tried another folder with only 3 .js files... None of them were reformatted and selecting the folder and trying again didn't help.  Again, opening each file in the IDE then running cleanup did reformat them.

**Comment by codecadwallader** [comment] 2015-09-23 11:22
There is a known issue with third party cleanup commands not always being available at the time of code cleanup (see #77).  In particular, with invoking ReSharper cleanups during a batch cleanup operation if ReSharper does not have the file model ready quickly, their cleanup command will not be available and it will silently fail to execute.  The larger the file, the more consistently a file will fail to cleanup.  If a file is already open, then the file model is usually loaded and the issue is not seen.

That issue has not been seen with the native cleanup command in Visual Studio, but it sounds similar to what you are seeing.

I have been unable to reproduce the issue, but I do not have a large JavaScript project to test against.  I do have a medium sized TypeScript project, but it does not exhibit the issue.

A few things to try:
1.  Enable CodeMaid->Options->Diagnostics mode, and check the Output window when the issue occurs to see if anything interesting is logged.
2.  Make sure CodeMaid->Options->Multithread operations is disabled.  This is off by default.
3.  Try running cleanup operations against a different JavaScript code base to see if you can reproduce the issue in multiple code bases.
4.  Export your settings, then reset to defaults, to see if there is anything configuration specific that may be causing the issue.

**Comment by jolsa** [comment] 2015-10-09 20:02
I created my own VS extension project that just executes "format document" and found it works for everything except Javascript files (regardless of the size of the project).  It will format Javascript files if they are already open.  But when opening and activating, I see the work "refreshing" at the top of the file.

There may be a work-around, but I haven't found one yet.

**Comment by codecadwallader** [comment] 2015-10-09 20:54
Interesting, thanks for going through the effort to prove out the issue like that with how VS formats JavaScript documents.  It certainly sounds like a readiness thing.  If you add some lag into the operation (e.g. open a file, wait 10 seconds, then clean it) - does it consistently work?  Not that "sleep" commands are the right solution, just curious as that could confirm the idea that the file isn't ready yet for processing at the time of formatting.

**Comment by jolsa** [comment] 2015-10-13 16:24
I tried the usual hacks... Sleep and DoEvents and I tried threaded approaches and nothing seemed to work.  I'm not even 100% certain that CodeMaid successfully issued the "Edit.FormatDocument" on any of my Javascript files before unless they were already open in the IDE.

The code I wrote opens and activates each document (my project only has Javascript in it) and I can see that the documents are never "ready" as far as Visual Studio 2015 is concerned until my method completes, but since it leaves the documents open if it wasn't able to execute the format, I run again and they all get formatted.

I'm going to try a couple other things then possibly resign to a 2 pass approach... Open all, then format all.

**Comment by codecadwallader** [comment] 2015-10-13 16:35
Erk.. thanks for the update.  The 2 pass approach may run you out of memory pretty quickly on larger projects.  Visual Studio grows in memory with every document open, but it grows a lot faster if others aren't closed.  It would be a little more convoluted, but what a callback approach?  Open document 1, kick off a timer that fires in 5? seconds to run the formatting and close.  Iterate across and open files along the way.

You could also test for command availability, and go back into the timer loop while the command is not available.  See https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/CodeCleanupManager.cs#L512 as an example of testing command state.

**Comment by jolsa** [comment] 2015-10-13 16:44
I'll take a look at it... The way I have my code written now, it closes any that are successfully formatted (no COMException thrown) which is everything but Javascript, so it leaves my 214 .js files open and a second pass (I created an option for "open documents only" finishes the job).

This is all on a copy of our actual solution because I'm going to do this for real after a release when everyone can check-in all code.  I'll make a first pass of "reformat" and a second pass with CodeMaid and all of it's extra cleanup features.  All of CodeMaid's cleanup seems to work on the Javascript files except the "Edit.FormatDocument".

With luck I'll never have to do this again, but I would like to find a more practical, viable solution in case I ever do.

**Comment by jolsa** [comment] 2015-10-13 20:08
The timer works, but not reliably.  I tried creating a timer for each document where the command .IsAvailable was false and tried putting them all into a list to cleanup after everything else was done.  The latter worked more reliably, but neither attempt got all the files.

**Comment by codecadwallader** [comment] 2016-03-17 16:30
Closing due to inactivity, please comment to reopen.

**Closed by codecadwallader** 2016-03-17 16:30 UTC
Labels: help wanted, not reproduced
