### ISSUE TITLE
Remove/Sort Usings Not Working With VS 2017 and .Net Core

### ISSUE THREAD

**Issue by jlbeard84** [codecadwallader/codemaid#416] opened 2017-03-21 15:26 UTC
### Environment
- Visual Studio version: 2017 Professional
- CodeMaid version: 10.2
- Code language: C#

### Description
I'm working on a project using Visual Studio 2017, C#, and .NET Core. When running CodeMaid cleanup, nothing happens to the using statements. Before moving to 2017, this same project was on 2015 Professional and cleanup still worked great. 

### Steps to recreate
1. Have a using statement that needs to be reorganized or removed.
2. Run CodeMaid cleanup.

### Current behavior
Using statements are not being cleaned up properly.

### Expected behavior
Using statements should be cleaned up.

**Comment by jlbeard84** [comment] 2017-03-21 15:27
I've identified the issue as CodeMaid is running the Visual Studio command "Edit.RemoveAndSort", whereas the command that works for me within 2017 is actually "EditorContextMenus.CodeWindow.RemoveAndSort". As a temporary workaround I've added this to the "Other cleaning commands" section and CodeMaid then cleans up as expected.

**Comment by codecadwallader** [comment] 2017-03-21 15:32
Awesome, thanks for reporting and finding a quick fix!

We did notice that starting in VS2017 when they merged the commands, the commands are frequently not available.  See #377 .  In my case it seemed to be tied to having ReSharper installed as well, do you happen to have that installed too?  I've been waiting for official releases for VS2017 (now out) and ReSharper (still in EAP) to see if either of them would address it natively.

Switching to a different command seems like a pretty simple fix and in a local test that worked for me as well.  Would you like the honor of submitting a pull request?  The relevant line of code:

https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/UsingStatementCleanupLogic.cs#L89

**Comment by jlbeard84** [comment] 2017-03-21 15:34
I was indeed working on a pull request to submit. And yes, I do too have ReSharper installed. Thanks!

**Closed** 2017-03-26 19:34 UTC
Labels: bug, feature: cleaning, reproduced, resolved

**Comment by ukod** [comment] 2019-05-31 12:17
The issue has been reproduced on vs 2019

**Comment by codecadwallader** [comment] 2019-06-04 12:56
@ukod I'm unable to reproduce it in VS2019.  I'm no longer using ReSharper so I'm not sure if that's a part of it.  If you're still seeing it can you please open a new issue along with more details?

**Comment by srberard** [comment] 2019-11-02 13:11
I was able to reproduce this in VS2019.  I resolved this by going into the CodeMaid settings and disabling and re-enabling the "Run remove and sort usings statement" setting.  Works as expected now.
