### ISSUE TITLE
CodeMaid 10.5 broke whitespace handling

### ISSUE THREAD

**Issue by alexdrl** [codecadwallader/codemaid#564] opened 2018-06-11 07:51 UTC
### Environment
- Visual Studio version: VS 15.7
- CodeMaid version: 10.5
- Code language: C#

### Description
PR #546 has broken whitespace handling in some scenarios. This test reproduces this result:
```cs
        /// <summary>
        /// If XML tag indenting is set, this should not affect any literal content. however,
        /// content after the literal should be indented as normal.
        /// </summary>
        [TestMethod]
        [TestCategory("Formatting UnitTests")]
        public void XmlFormattingTests_DoesIndentAfterLiteralContent2()
        {
            var input =
               "<summary> Return the model in XML format. </summary>" + Environment.NewLine +
               "<remarks>" + Environment.NewLine +
               "This method is cloned from the <see cref=\"DomainDSLSerializationHelperBase\"/> generated class." + Environment.NewLine +
               "The purpose of this method is to add the" + Environment.NewLine +
               "</remarks>";

            var expected =
               "<summary> Return the model in XML format. </summary>" + Environment.NewLine +
               "<remarks>" + Environment.NewLine +
               "    This method is cloned from the <see cref=\"DomainDSLSerializationHelperBase\"/> generated class." + Environment.NewLine +
               "    The purpose of this method is to add the" + Environment.NewLine +
               "</remarks>";

            Settings.Default.Formatting_CommentXmlValueIndent = 4;
            Settings.Default.Formatting_CommentXmlKeepTagsTogether = true;
            Settings.Default.Formatting_CommentXmlSpaceTags = true;

            // First pass.
            var result = CommentFormatHelper.AssertEqualAfterFormat(input, expected);

            // Second pass.
            CommentFormatHelper.AssertEqualAfterFormat(result, expected);
        }
```
A line get created after the remarks line. also, there are a lot of tests also failing...

**Comment by codecadwallader** [comment] 2018-06-11 11:05
Thanks for reporting the issue.  In regards to failing tests, there's a known issue #467 with the integration test suite which is the bulk of the tests.

@willemduncan want to take a look at the whitespace issue mentioned?

**Comment by alexdrl** [comment] 2018-06-11 11:35
@codecadwallader The tests that failed in my environment were the UnitTests Project, which I thought that they will be working. For executing them, I deselected the runsettings file, so they won't got ignored.

The test that I attached is copied from https://github.com/codecadwallader/codemaid/blob/d44c6d13b94453550b0a7b1266af6b20fcc48ae0/CodeMaid.UnitTests/Formatting/XmlFormattingTests.cs#L166 so I thought that those Project tests worked before.

**Comment by willemduncan** [comment] 2018-06-12 13:40
Strange, I put the PR with all tests succeeding. However, the current way of using the `Settings.Default` for testing the formatting is prone to problems. It assumes the user running the tests has the "default" settings, except where explicitly overridden in the test case. This will be fixed in an upcoming PR.

Either way, I notice that somehow the content of the failing test you pasted does not match the test description: "XmlFormattingTests_DoesIndentAfterLiteralContent" should be a test with a literal node (where content is preserved without formatting, eg a `<code>` block). But the code you pasted seems to test XML tag spacing. What is exactly failing?

**Comment by willemduncan** [comment] 2018-06-14 10:06
Aha I see, sorry, I missed the fact that you put a new test case there. I've managed to reproduce it and will fix it.

**Comment by alexdrl** [comment] 2018-06-15 08:07
Thank you for the quick fix, sorry for not explaining that this was a new test. Hoped that the new test made you reproduce the error.

Should we expect a hotfix?

**Comment by willemduncan** [comment] 2018-06-15 09:04
I can only fix the code, releases depend on @codecadwallader. Thanks for reporting the issue!

**Comment by Starkie** [comment] 2018-10-04 11:33
Hi
Any news on when this fix will be deployed? It's really cumbersome to keep installing the previous version so our analyzers don't fail... 😔

**Comment by Arekssio** [comment] 2018-10-17 11:54
@codecadwallader, could you please check this out? We also need this change to be deployed, since our style analysers alert us everytime because of this bug.. :/

**Comment by codecadwallader** [comment] 2018-10-21 20:44
Noted, thanks for letting me know.  I was planning to roll this into a larger upcoming v11, but will instead look to push a smaller v10.6 out sooner.

@Starkie or @Arekssio if you want to test that intended build for v10.6 you can grab it directly from our CI feed here: http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/  I'd appreciate the confirmation that it does indeed resolve the issue.

**Comment by Starkie** [comment] 2018-10-22 10:23
Hi, thanks for the answer @codecadwallader !

Yep, it seems that the problem was solved. 
But, we found we had another issue: In single line comments when a single space is used at the start of the comment, it turns it on two spaces.

For example:
```#c
// This is a comment.
```
Turns into:
```#c
//  This is a comment.
```

Using the StyleCop Analyzers, it alerts us, because only one space is expected.

Is there any way to configure the number of spaces inserted?

**Comment by codecadwallader** [comment] 2018-10-28 19:49
Hmm, thanks for the response @Starkie but it sounds like introducing that bug would be worse than the original.  I've been unable to reproduce it so far.  It started appearing only with the latest build?  Can you attach an export of your settings (I'm using default settings) in case there's anything specific to that?

**Comment by Starkie** [comment] 2018-10-29 08:13
Sure, here it goes. We tested against the v10.5.133. I'll try later if I can, with the newest [v10.5.137].

[CodeMaid.zip](https://github.com/codecadwallader/codemaid/files/2524358/CodeMaid.zip)

**Comment by codecadwallader** [comment] 2018-11-03 14:06
Thanks for the configuration file, I can reproduce the issue with that.  @willemduncan can you please take a look?

**Comment by willemduncan** [comment] 2019-02-11 07:12
I'm late to the game, I see. Didn't expect a new issue to show up here, will see what I can do!

**Comment by codecadwallader** [comment] 2019-04-13 23:15
Taking a look at the unit tests `XmlFormattingTests_AddSpaceToTagContentShouldLeaveNoTrailingWhitespace2` which is currently ignored will still fail.  It's not leaving behind trailing whitespace (original reported issue) nor do I see the doubled leading whitespace (issue introduced by first fix).  In particular it appears the indentation setting is not being respected.  @willemduncan do you mind taking a look if there's anything further needed?

**Comment by Starkie** [comment] 2019-04-16 06:48
We've tested the v11.0.188 build from the CI. Both issues seem to have resolved, but a new one seems to have arised... 😅

When formatting a comment with at least a section that is multiline, it starts adding backlashes each time is formatted.

For example:

Original comment
```cs
/// <summary> This is a summary. </summary>
/// <param name="param"> This is a multiline comment for the parameter param. It is going to add backlashes. </param>
/// <returns> The returns. </returns>
```

Then, after the first time I format the document:
```cs
/// <summary> This is a summary. </summary>
/// <param name="param">
///     This is a multiline comment for the parameter param. It is going to add backlashes.
/// </param>
///        /// <returns> The returns. </returns>
```

A second time:
```cs
/// <summary> This is a summary. </summary>
/// <param name="param">
///     This is a multiline comment for the parameter param. It is going to add backlashes.
/// </param>
///        /// ///
/// <returns> The returns. </returns>
```

From then on, the line of backlashes will grow each time the document is formated.

Should we keep using this issue or create a new one?

**Comment by willemduncan** [comment] 2019-04-18 08:28
Create a new issue and I'll get right on it.

**Comment by codecadwallader** [comment] 2019-04-18 10:01
Thanks all! :)  That GitHub feature is indeed cool.

**Comment by willemduncan** [comment] 2019-04-22 18:09
Got a bit worried when unexpectedly finding this in the 'open' issues list again, but I see I simply forgot to close the issue last week.

**Closed by willemduncan** 2019-04-22 18:09 UTC
Labels: feature: formatting
