### ISSUE TITLE
CodeMaid + ReSharper 9 fails on sorting/removing using statements on VS 2013

### ISSUE THREAD

**Issue by sgisbert** [codecadwallader/codemaid#79] opened 2015-02-18 15:41 UTC
Hi,

I have Visual Studio 2013 with Resharper installed, and I'm getting this error on cleanup:

[CodeMaid Handled Exception 04:37:06 PM] Stopped cleaning 'VarnishPurge.cs': System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UsingStatementCleanupLogic.SortUsingStatements(Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClassb.<Cleanup>b__9()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)

And a similar one for "Sort usings".

When you go to CodeMaid settings and uncheck "Cleaning -> Visual Studio -> Run remove using statements" and "Cleaning -> Visual Studio -> Run sort using statements", then it works again.

I have noticed that when you disable Resharper, the remove/sort usings works again, and also, that the Edit menu in VS is modified with R# active, so that makes me think that, somehow, R# removes/changes the native methods for:

_package.IDE.ExecuteCommand("Edit.RemoveUnusedUsings", String.Empty);
_package.IDE.ExecuteCommand("Edit.SortUsings", String.Empty);

I'm not using R# tird party format. Just installed with default settings and started to play around.

Great tool, anyway!

Kind Regards,
Sergi

**Comment by codecadwallader** [comment] 2015-02-18 20:17
This is a known issue with ReSharper 9 that they have fixed in ReSharper 9.0.1. Please grab the latest version of ReSharper and that should(tm) get things working again for you. :)

**Comment by codecadwallader** [comment] 2015-02-18 20:17
Duplicate of #43

**Closed by codecadwallader** 2015-02-18 20:17 UTC

**Comment by sgisbert** [comment] 2015-02-19 08:46
It works perfectly!

Thanks so much.
Sergi

**Comment by codecadwallader** [comment] 2015-02-19 11:34
Glad to hear it :)
