### ISSUE TITLE
Windows Forms Designer Issue

### ISSUE THREAD

**Issue by Andy65** [codecadwallader/codemaid#217] opened 2016-02-23 16:58 UTC
With _version 0.9.0_ I am finding that changes I make to a new Windows Form (with no controls on it) are not getting saved to the .Designer.cs file for that form e.g. I change the Text property hit save and then check the .Designer.cs file and note that the designer has not recorded the change to the Text property. I have confirmed this to be a problem with CodeMaid by disabling the extension and then retrying the operation and noting that the designer changes are now saved properly and then re-enabling the extension and noting that the problem returns. My config file is attached.

[CodeMaid.zip](https://github.com/codecadwallader/codemaid/files/143008/CodeMaid.zip)

**Comment by codecadwallader** [comment] 2016-02-23 17:01
Thanks for reporting the issue.  We recently closed a similar issue that we were unable to reproduce.  Can you please take a look at it and see if it makes sense to reopen that one, or start fresh with this issue?  #180

**Comment by Andy65** [comment] 2016-02-23 18:35
I would reopen the existing issue. I think I may have found the setting
causing the problem whilst attempting to reproduce the issue at home. I did
the following:

   1. Created a new Windows Forms project;
   2. Edited the Text property of the form, saved and checked the
   .Designer.cs file and noted that the change had been saved;
   3. Checked the CodeMaid options and saw that Reorganizing -> Regions ->
   Remove existing regions was unchecked (I have it checked at work) so I
   checked it; and
   4. Edited the ShowIcon property and noted that the change did not now
   get recorded in the .Designer.cs file; so
   5. I once again unchecked the Remove existing regions option; and
   6. Edited the ShowIcon property and noted that the change was now
   properly recorded in the .Designer.cs file.

Is it possible that in the code you are blocking the propagation of an
event and thus the code in Visual Studio that saves the designer changes
never actually executes?
Anyway, hopefully you can now reproduce.

Kind Regards
Andy


On Tue, 23 Feb 2016 at 17:01 Steve Cadwallader <notifications@github.com>
wrote:

> Thanks for reporting the issue. We recently closed a similar issue that we
> were unable to reproduce. Can you please take a look at it and see if it
> makes sense to reopen that one, or start fresh with this issue? #180
> <https://github.com/codecadwallader/codemaid/issues/180>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codecadwallader/codemaid/issues/217#issuecomment-187792232>
> .
>
-- 
Kind Regards

Andy

**Comment by codecadwallader** [comment] 2016-02-23 19:40
Closing this issue in favor of continuing existing issue #180

**Closed by codecadwallader** 2016-02-23 19:40 UTC
