### ISSUE TITLE
Re-Organizing Not Working

### ISSUE THREAD

**Issue by RealDotNetDave** [codecadwallader/codemaid#191] opened 2015-12-15 18:24 UTC
For awhile now the re-organizing on save has not been working. I reset options. I deleted CodeMaid and then re-installed and still not working.

Anyone else seeing this?

Thanks,
David McCarter
Microsoft MVP

**Comment by scoobadog** [comment] 2015-12-16 08:46
I'm also seeing this issue. For me it started happening after VS2015 Update 1.

**Comment by codecadwallader** [comment] 2015-12-17 01:38
Thanks for reporting the issue.  So far I have been unable to reproduce it.  My test was to enable both automatic cleanup on save and automatic reorganization on save, then save a C# file using Visual Studio 2015 Update 1.  It worked as expected (i.e. reorganized and cleaned the file).

If either/both of you could provide the following information it may be very helpful in looking into it further:

- Visual Studio version (@RealDotNotDave - are you using VS2015 Update 1 and did you see it prior?)
- CodeMaid version
- CodeMaid settings (user, solution as applicable)
- Steps to reproduce if different than above
- Was this working as expected with a different version?
- I'm assuming reorganization works fine if you invoke it manually, it is only during automatic cleanup on save?
- Does this happen when you directly invoke a save, or only when you indirectly invoke a save (i.e. start a build which causes files to save)?
- Any additional notes, images, etc.

**Comment by scoobadog** [comment] 2015-12-29 05:21
I tried to create a simple solution where I could reproduce this issue. I don't know what happened but suddenly reorganize started working again. When it was broken it didn't work when it was either manually or indirectly invoked. CodeMaid version I'm using is 0.9.0.

**Comment by codecadwallader** [comment] 2015-12-29 17:31
@scoobadog Thanks for the update that it's working for you now.  I wonder if you had solution specific settings with the original solution that may be the clue as to the difference between them?

**Comment by codecadwallader** [comment] 2016-01-30 19:17
Closing due to inactivity and as @scoobadog said it was no longer an issue for him.

**Comment by RealDotNetDave** [comment] 2016-02-01 18:45
Ok. The contract I’m working on won’t let me reorganize their source files so I have not used this in awhile. But I am still having some issues with it with my own code. I am seeing that it’s not cleaning/ re-orginizing the import statements. I will keep looking at it.

David

**Comment by codecadwallader** [comment] 2016-02-01 21:02
Ok, reopening accordingly.  Keep me posted if there's anything you find or if there's any more of the information above that you can provide.

**Comment by codecadwallader** [comment] 2016-03-19 15:11
One other thought came to mind - we deliberately do not reorganize any files that contain #pragma statements .  See #200 for details.  Any chance that was the case?  It wouldn't explain a recent change - that's been the case for several versions.

**Comment by scoobadog** [comment] 2016-03-29 05:16
I checked my commits from the end of December and I couldn't find any files that have #pragma, #region or #if statements in them. I was also aware of #200 at the time I had the issue.

**Comment by codecadwallader** [comment] 2016-03-29 11:42
Ok, it was worth a shot.. thanks for the additional details.

I have seen some of our reorganization integration tests intermittently fail but I'm not confident it is related to this issue.  When you were seeing this issue last December, do you happen to know if you noticed any irregular behavior (e.g. would not reorganize one time, but would the next)?

**Comment by scoobadog** [comment] 2016-03-31 10:58
I'm not 100% sure but I think that I was able to sometimes reorganise the files (possibly after Visual Studio restart). Although most of the time they refused to reorganise.

**Comment by codecadwallader** [comment] 2016-04-10 11:37
I've added some more detailed diagnostics around the CodeReorganizationAvailabilityLogic class.  It will now print a diagnostic message with the condition that caused a document to be excluded from reorganization.  This can be seen if you enable CodeMaid->Options->Diagnostics mode and look in the Output window's CodeMaid pane.  Note:  This will only catch if reorganization is not running at all, not if it is running and taking no action.

If you can reproduce the issue at all regularly, it would be very helpful to test if closing the CodeMaid Spade tool window has any impact.  When that window is open it will preload the code model (so it can display it) but if the window is closed the code model will not be loaded until cleanup or reorganization is started.

**Comment by scoobadog** [comment] 2016-04-11 09:09
I can't currently test this as I'm currently working on a code base where reorganise would cause lots of merge confilicts. When I get back to the project where I encountered this issue I'll try to remember to monitor the diagnostics pane.

**Comment by FCSz** [comment] 2016-05-14 00:38
I also cannot get CodeMaid to reorganize my source code files.
I have posted an example Visual Studio 2015 Community edition at
https://github.com/FCSz/testSemanticVersion

Please help. I would really like to use reorganize.

**Comment by codecadwallader** [comment] 2016-05-14 02:47
@FCSz it looks like your solution is C++.  Unfortunately reorganization currently only supports C# and VB.

**Comment by codecadwallader** [comment] 2016-12-31 10:54
Closing due to inactivity.

**Closed by codecadwallader** 2016-12-31 10:54 UTC
Labels: bug, feature: reorganizing, not reproduced
