### ISSUE TITLE
Possible Interaction with Resharper Autocomplete causes Underscore instead of completed word.

### ISSUE THREAD

**Issue by stihl716** [codecadwallader/codemaid#305] opened 2016-06-13 15:00 UTC
### Environment
- Visual Studio version: VS 2015 Pro Version 14.0.25123.00 Update 2
- CodeMaid version: !0.1
- Code language: C#

### Description
I use both CodeMaid and Resharper (Ultimate 2016.1.2).  With CodeMaid Cleanup on Save enabled, if I type a few characters in a code window and then press Tab to select the current value in the auto complete list, the text I've typed is replaced with an underscore character.

### Steps to recreate
Starting with both Resharper and CodeMaid Automatic Cleanup on Save enabled
-Type the first few characters of a class name (seems to only happen with classes in my projects)
-Press the Tab key to autocomplete.

### Current behavior
-Instead of the class name being shown, the typed text is changed to an underscore.

### Expected behavior
-The typed text should be replaced with the selected item in the list.

### Additional Informatoin
If I suspend Resharper the problem doesn't happen.  
If I restart Resharper and set turn off CodeMaid Automatic Cleanup on Save, it doesn't happen.
It only happens when both are turned on. 

I have a screen capture demonstrating the problem.

**Comment by codecadwallader** [comment] 2016-06-15 12:49
Thanks for reporting the issue.  I am a ReSharper user as well and I have not been able to reproduce this problem.  It sounds a little bizarre because no save activity should be having when using IntelliSense, and CodeMaid has no feature sets that interact with the IntelliSense services.

Since I can't reproduce the issue, can you provide some additional information such as the screen capture you mentioned, relevant settings from ReSharper/CodeMaid, and/or a sample code base that exhibits the issue?

Something else to try would be if you can exhibit the problem in a sample project solution (vs. your primary development solution).

**Comment by stihl716** [comment] 2016-06-21 15:08
I did put some effort towards trying to simple-case the problem but it was taking more time than I could afford to spend.  There may be something to do with the fact that we have both Silverlight and WPF projects in our solution.  When I removed all of the Silverlight projects, the problem would (sometimes) go away.  

I'm attaching a zip containing my Resharper settings, Codemaid settings and the screen capture showing the behavior.


[ResharperCodeMaid.zip](https://github.com/codecadwallader/codemaid/files/325895/ResharperCodeMaid.zip)

**Comment by codecadwallader** [comment] 2016-06-21 19:51
Thanks for the information.  The video looks like something is causing the document to be saved when you press tab.  Do you have any other extensions also installed (e.g. unit test runner) that may be trying to force a file save while using IntelliSense?  If you disable CodeMaid, do you ever see other scenarios where IntelliSense is triggering a file save?

**Comment by stihl716** [comment] 2016-06-22 19:26
I see that now that you point it out.  Interesting behavior.  I haven't installed anything specifically to do that.  

I've disabled all of the extensions I can (some can't be disabled) except CodeMaid and R# and the problem still happens.  If I disable either of those, it doesn't happen.  Here's a list of enabled packages and extensions on my machine:

Microsoft Visual Studio Professional 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Visual Basic 2015   00322-50051-29936-AA366
Microsoft Visual Basic 2015

Visual C# 2015   00322-50051-29936-AA366
Microsoft Visual C# 2015

Visual C++ 2015   00322-50051-29936-AA366
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.209.60613.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

CodeMaid   10.1.93
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.31.0
TypeScript tools for Visual Studio

**Comment by codecadwallader** [comment] 2016-06-22 20:55
That is strange.  Another thing to test - I see you have CodeMaid setup to enable ReSharper's cleanup when it runs its cleanup.  If you flip that setting does it change the behavior?  Perhaps it's an odd loop where ReSharper cleanup running while IntelliSense is up gets into a bad state.

**Comment by stihl716** [comment] 2016-06-23 14:45
No.  If I uncheck that option, the behavior still occurs.

**Comment by codecadwallader** [comment] 2016-06-23 15:03
That seems like a fairly straightforward list of other extensions, nothing jumped out (e.g. NCrunch as a unit test runner I think can trigger file saves).  I'm at a bit of a loss on why a document save is getting triggered.  We have a number of users (myself included) that use ReSharper and CodeMaid together and haven't seen that issue.  Do you happen to have a second machine where you can reproduce the issue, or is it isolated to this one setup?

**Comment by stihl716** [comment] 2016-06-24 19:30
I asked a colleague to try and repro and he couldn't.  I've attached his resharper settings and CodeMaid settings.
[Env2.zip](https://github.com/codecadwallader/codemaid/files/332447/Env2.zip)

**Comment by stihl716** [comment] 2016-06-28 13:41
FYI, I opened a case with Resharper previously.  Here's the link:   https://youtrack.jetbrains.com/issue/RSRP-459214

I asked them if they had any process that tries to save but they haven't responded.

**Comment by stihl716** [comment] 2016-06-29 13:18
FYI, 
The Resharper case has been updated today with a priority of "Show Stopper".  I guess they found something or are at least taking it seriously enough to look into it further.

**Comment by stihl716** [comment] 2016-06-30 13:26
Latest from Resharper: they've reproduced the problem and are looking for a fix.

**Comment by codecadwallader** [comment] 2016-06-30 14:02
Wonderful news, thanks for hunting this down and the updates!

**Comment by Swizzy** [comment] 2016-08-14 10:16
This issue can now be closed i would say, as it's been fixed in Resharper, and is completely unrelated to CodeMaid, the fix will roll out in the 2016.2 update, it can be downloaded from here in the meantime for those wanting a fix asap: https://confluence.jetbrains.com/display/ReSharper/ReSharper+2016.2+EAP

**Comment by codecadwallader** [comment] 2016-08-14 13:10
Excellent, thank you!

**Closed by codecadwallader** 2016-08-14 13:10 UTC
Labels: bug
