### ISSUE TITLE
Windows Form designer does not save changes

### ISSUE THREAD

**Issue by DarkfireHellspawn** [codecadwallader/codemaid#180] opened 2015-11-06 11:04 UTC
Hi,

I am facing a problem where the Windows Form designer does not save changes and resets the form back to the previous state.

This only occurs after the first debugging session. If I disable the CodeMaid extension it works perfectly.

I am using Visual Studio 2015 on Windows 10 x64.

Thanks.

**Comment by codecadwallader** [comment] 2015-11-06 12:13
Thanks for reporting the issue.  Unfortunately I have been unable to reproduce it so far.

Some additional information that may help:

- CodeMaid version 
- Code excerpt/file (if applicable) 
- Steps to reproduce 
- Was this working as expected with a different version? 
- Any additional notes, images, etc.

**Comment by DarkfireHellspawn** [comment] 2015-11-06 13:10
* CodeMaid version: 0.8.1
* Steps to reproduce:

1. Create a new Windows Form project
2. Add a button (or any other control) to Form1
3. Save
4. Right-click the form and select "View Code"
5. Close Design tab
6. Right-click the code and select "View Designer"
7. Copy and paste the previously added control
8. Save
9. Repeat steps 5 and 6
10. The second control has gone

No matter what I do from then on, any changes, whether they are property changes or adding controls, will not be preserved.

I don't know if it worked with a different version, sorry. :)

**Comment by codecadwallader** [comment] 2015-11-21 12:42
I've had difficulty reproducing this, but I have seen it twice now.  Investigating..

**Comment by codecadwallader** [comment] 2015-11-21 13:04
I have a hunch.. can you please try disabling the following CodeMaid option, and let me know if you are still able to reproduce the issue?

Remove->"Remove end of file trailing new line"

Once I disabled this setting, I was no longer able to reproduce the issue.  That same setting has a known workaround for C++ resource files and I'm wondering if the same is needed for VB.

**Comment by DarkfireHellspawn** [comment] 2015-11-21 13:09
I am using C#, does this matter?

**Comment by codecadwallader** [comment] 2015-11-21 13:18
That's good to know.. not sure why I got VB in my head.  Same question still applies though, does removing that setting resolve the issue for you?

**Comment by DarkfireHellspawn** [comment] 2015-11-23 12:13
I disabled "Remove end of file trailing new line". The issue still occurs.

**Comment by codecadwallader** [comment] 2015-11-23 12:29
How reliably are you able to reproduce it?  I saw it about half the time with VB, and never with C#.

If you can consistently see the issue, here's what you could do to help isolate the issue:

Export your CodeMaid settings.
Disable different cleanup actions (e.g. Remove unused using statements)
Repeat the steps above.

That's the approach I took that took me to a specific setting with VB which I'll continue to investigate.  When you're done you can import your settings to get back to a clean slate.

In particular I would recommend focusing on the 'Visual Studio' configuration options followed by the 'Remove' cleanup actions.

**Comment by DarkfireHellspawn** [comment] 2015-11-23 12:32
I can reproduce it every time. I'll try to find the culprit setting.

**Comment by DarkfireHellspawn** [comment] 2015-11-23 12:50
Hmm, well, that's interesting. I reset to defaults in CodeMaid and set it up again and now it's working perfectly.

I have attached my old and new settings.
[CodeMaid.config.txt](https://github.com/codecadwallader/codemaid/files/41559/CodeMaid.config.txt)
[OldCodeMaid.config.txt](https://github.com/codecadwallader/codemaid/files/41560/OldCodeMaid.config.txt)

**Comment by codecadwallader** [comment] 2015-11-23 13:03
Resetting to defaults would have turned off automatic cleanup on save.  I bet with that disabled you won't see any issues as CodeMaid won't be running a cleanup as the designer saves updates.

**Comment by DarkfireHellspawn** [comment] 2015-11-23 13:04
I turned it back on after I reset.

**Comment by DarkfireHellspawn** [comment] 2015-11-23 13:06
I have no idea what it was (maybe something from an older version?).

**Comment by DarkfireHellspawn** [comment] 2015-11-25 13:27
I have found the culprit: Reorganizing->"Run reorganize at start of cleanup".

Once I enable it, designer changes are not preserved. Disabling it allows changes to be saved.

**Comment by codecadwallader** [comment] 2015-11-25 15:43
That makes a lot of sense, thanks for discovering it.  I should be able to look at it further over the holiday weekend.

**Comment by codecadwallader** [comment] 2015-11-26 12:49
Unfortunately even with importing your old settings I'm still unable to reproduce the issue.  Re-reading some of the original comments to see if I'm forgetting anything you mentioned a debugging session on the original report, but it's not in the steps to reproduce.  Is that something you found wasn't required to exhibit the issue?  I'm following the steps to reproduce as written (e.g. never closing the code window).

**Comment by codecadwallader** [comment] 2016-01-30 19:18
Closing due to inactivity.  Please feel free to comment and we can reopen this issue.

**Comment by codecadwallader** [comment] 2016-02-23 19:39
Reopening this issue based on additional information provided by @Andy65 on #217

**Comment by codecadwallader** [comment] 2016-02-24 19:43
I've now reproduced the issue based on the additional information.  I've confirmed this issue is tied to the combination of enabling all of the following settings:
1. Auto cleanup on save
2. Auto reorganization during cleanup
3. Remove existing regions during reorganization

These options were all enabled in the OP's settings as well.

The designer file contains a `#region Windows Form Designer generated code`, so I suspect what is happening is that as requested CodeMaid is removing that region and it is interrupting the form designer's workflow causing changes to be lost.

Investigating further.  The .designer.cs file itself shouldn't(tm) be touched based on default cleanup exclusions..

**Comment by codecadwallader** [comment] 2016-02-24 20:40
Confirmed the .designer.cs file is not being touched by CodeMaid, which is correct behavior as it is listed in the exclusions.

The Form class will contain a default constructor in order to call `InitializeComponent`.  The removal and re-insertion of this region appears to be what interrupts persistence of designer edits.

The list of above settings should also include:
4. Insert regions during reorganization

**Comment by codecadwallader** [comment] 2016-02-27 12:24
I've found that this issue occurs when you trigger the save with the designer window active, but not when you trigger the save with the code window active.  We generally try to enforce that a code window is open and active as several of the cleanup commands require that to run successfully.  It appears that cleanup is running improperly when the code file is in the background or not open at all.

The straight forward fix I've just pushed is that when the designer window is active, saving the file will not cause the code to be cleaned.  The code window will have to be active for cleanup to proceed.  There wasn't any good way to distinguish the two window types through the API other than by the file caption which is hacky, but functional.

This fix will be present in the next release, thanks again @DarkfireHellspawn and @Andy65 for all the help tracing it down.

**Comment by codecadwallader** [comment] 2016-03-06 13:37
This fix is now available in the latest beta here: https://github.com/codecadwallader/codemaid/releases/tag/v0.9.0.2-beta

**Closed by codecadwallader** 2016-03-06 13:37 UTC
Labels: reproduced, resolved

**Comment by andrewcartwright1** [comment] 2017-03-11 21:57
This issue looks to be continuing in 10.2.7
Using the same replication steps as above but instead with custom controls and custom properties, if I save/build in designer code view works fine, if i save/build in designer it resets them
