### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [codecadwallader/codemaid#816] opened 2021-06-17 20:22 UTC
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by scottkuhl** [comment] 2021-06-17 22:20
- [Writing Visual Studio Extensions with Mads - 64bit extensions for Visual Studio 2022](https://www.youtube.com/watch?v=L8b3kFriwCs)
- [Writing Visual Studio Extensions with Mads - Splitting extensions for Visual Studio 2022](https://www.youtube.com/watch?v=-PKIPTW6km0)

**Comment by Eli-Black-Work** [comment] 2021-06-18 06:52
Also looking for this 🙂

**Comment by Eli-Black-Work** [comment] 2021-06-18 06:53
Guess we can tell who the early adopters are, haha XD

**Comment by wertzui** [comment] 2021-06-22 07:06
There is already a PR for this #817

**Comment by codecadwallader** [comment] 2021-06-23 11:01
Thanks all for jumping on this quickly.  There are indeed some compatibility breaking changes in VS2022.  I believe last I heard it was expected that for all extensions the code would have to be branched and separate releases made targeting different versions of Visual Studio.  For the time being I would keep the `dev` and `release` branches pointing to the existing VS2017/VS2019 version, tied into the CI pipeline, etc.  We'll end up creating a new `vs2022` branch and I'm still thinking about the other implications.

It looks like 2 PRs have started, #817 and #818.  It looks like #818 might have gone farther with following recommendations.  Thanks for links @scottkuhl as there may be some non-obvious changes we need to make to support the changes.  Testing those out and seeing what issues come up (e.g. the settings dialog not opening in one) is super helpful and appreciated. <3

**Comment by codecadwallader** [comment] 2021-07-30 21:36
Hey all, I've been working on the VS2022 upgrade.  I decided to start fresh on a new `vs2022` branch and follow the instructions for multi-targeting VS versions based on https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022 vs. building on top of #818 which is VS2022-only.  I have to say these are far more detailed instructions than have ever been provided before and I really appreciate them.

## What is done
- "Modernize your projects".  I attempted this a few years ago and encountered several issues at the time.  This worked pretty smoothly this time around and closes #643.  CodeMaid still worked as expected at this checkpoint.

- Created a shared project called `CodeMaidShared`, migrated code and linked resources.  Deviations:
-- I haven't done the same with CodeMaid.IntegrationTests yet.  I wanted to prove it out with the main project first.
-- Instead of moving all the resource files and having both projects utilize links to the new location, I left all files in their original location and only have the new project performing links.  This seems like it should(tm) be the same difference to me and saved a chunk of effort.

- Created the new VS2022 VSIX called `CodeMaid.VS2022` with necessary links/updates.

- VS2017 can compile and generate the original CodeMaid VSIX successfully.
- VS2022 can compile and generate the new CodeMaid 2022 VSIX successfully.

- i.e. the migration instructions above are complete.

## Where it stands
The extension loads successfully into the VS2022 Preview IDE, but that's about it.  Some very limited functionality is working (e.g. build progress tool window) but most core functionality is not working for different reasons.

### Cleaning/Joining
`System.NotImplementedException` is thrown when trying to use the `EnvDTE.TextDocument.ReplacePattern` API.  I'm curious if this is related to switching from explicit EnvDTE references to the general Microsoft.VisualStudio.SDK package and if it's not targeting the correct version or needs an explicit binding redirect.

### Digging
`FileNotFoundException: Could not load file or assembly 'SteveCadwallader.CodeMaid, Culture=neutral' or one of its dependencies. The system cannot find the file specified.`  I'm curious if this is related to switching to a shared project and the XAML references are not working as expected.  The same issue happens for other UI dialogs (e.g. Options and About dialogs).

### Reorganizing
`System.NotImplementedException` is thrown when trying to use the `EnvDTE.EditPoint.FindPattern` API.  This is very similar to above.

## What is next
I'll be reaching out to Microsoft to see if they can provide any technical guidance on those issues.  I'm sure we can work through them but if they have any hints that would certainly help.  The `vs2022` branch is published and I will gladly accept PRs against it.

**Comment by codecadwallader** [comment] 2021-09-03 12:22
An update:

I've been working with Microsoft on some of the issues above.  I think we've got the Digging issue figured out but unfortunately with Preview 3.1 I'm no longer able to get the extension to load (i.e. a step backwards) so I haven't been able to test it.

The current error:

```
 <entry>
    <record>2198</record>
    <time>2021/09/03 12:14:20.645</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [CodeMaidPackage]Source: &apos;SteveCadwallader.CodeMaid&apos; Description: Method not found: &apos;Void EnvDTE._dispBuildEvents_OnBuildBeginEventHandler..ctor(System.Object, UIntPtr)&apos;.&#x000D;&#x000A;System.MissingMethodException: Method not found: &apos;Void EnvDTE._dispBuildEvents_OnBuildBeginEventHandler..ctor(System.Object, UIntPtr)&apos;.&#x000D;&#x000A;   at SteveCadwallader.CodeMaid.CodeMaidPackage.&lt;RegisterEventListenersAsync&gt;d__36.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at SteveCadwallader.CodeMaid.CodeMaidPackage.RegisterEventListenersAsync()&#x000D;&#x000A;   at SteveCadwallader.CodeMaid.CodeMaidPackage.&lt;InitializeAsync&gt;d__32.MoveNext() in C:\src\codemaid\CodeMaidShared\CodeMaidPackage.cs:line 202&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()</description>
    <guid>{4C82E17D-927E-42D2-8460-B473AC7DF316}</guid>
    <hr>80131513</hr>
    <errorinfo></errorinfo>
  </entry>
```

While I'm waiting to hear back if anybody has ideas I'm all ears.  Also if you want to play around the `vs2022` branch is available.  We'll get there!

**Comment by kotx** [comment] 2021-09-19 19:48
@codecadwallader Did you manage to work out the error you mentioned above? Would love to know the progress on this.

**Comment by TonyValenti** [comment] 2021-09-23 11:17
I recently started using VS2022 Preview 4 and I am _really_ missing the "Find in Solution Explorer" feature.
I'm really hoping CodeMaid gets enabled soon.

**Comment by wertzui** [comment] 2021-09-23 12:23
> I recently started using VS2022 Preview 4 and I am _really_ missing the "Find in Solution Explorer" feature.
> I'm really hoping CodeMaid gets enabled soon.

There is a built in Hotkey for that.
On my German system it is `CTRL` + `ß`, `s`
On English systems, it should be `CTRL` + `[`, `s` according to https://stackoverflow.com/a/55025095/1378307

**Comment by codecadwallader** [comment] 2021-09-24 12:59
@kotx I did get through the SetSite error.  It was actually just user error on my part, wrong startup project selected 🤦 

I'm making progress on issue 2 (UI resolution using a shared project) but it's still in back and forth with Microsoft.  It will mean refactoring the paths for a number of items but in particular trying to set the `Application.ResourceAssembly` which seems to be needed in shared contexts is not working as expected and provides the following error message:

> IOException: Assembly.GetEntryAssembly() returns null. Set the Application.ResourceAssembly property or use the pack://application:,,,/assemblyname;component/ syntax to specify the assembly to load the resource from.

I haven't made any headway on related issues 1 and 3 about not implemented APIs.  I've been hoping newer preview editions would catch up and fill out more of the API but as of Preview 4.1 they are still not implemented.

It's slow going, but continuing to work on it and as always help is welcome!

**Comment by codecadwallader** [comment] 2021-09-28 12:50
A lot of the challenge we're running into is trying to switch to a new shared project infrastructure in order to support both VS2017/VS2019 and VS2022 which introduces breaking compatibility changes.  I still think this is the right way to go going forwards and is the recommended and documented path too, however a shortcut could be a direct upgrade to a VS2022-only version of CodeMaid.  This would only be in a branch and would get abandoned eventually.  It would be interesting to see if it encountered some of the same API issues or if they were only an issue with the shared project approach.

**Comment by codecadwallader** [comment] 2021-10-07 12:51
Status update: it looks like we've got issue 2 (UI resolution) worked out thanks to some help from Microsoft.  🎉  We needed to utilize `Assembly.GetExecutingAssembly` vs. GetEntryAssembly and the timing was off for when we were adding it.  This seems to be required for VS2022 only, VS2017 doesn't need it but also doesn't seem to be harmed by it in some quick regression testing.

So what that all of the UI elements are appearing!  The Spade (digging) window is not showing any content yet because while the code model is building successfully when we go to find the regions (not a part of the code model) the same missing API `FindPattern` that is issue 1 and 3 is used and throws an error.

I'm continuing to work with them and all the latest changes are pushed up into the `vs2022` branch for anyone who would like to explore.

**Comment by TonyValenti** [comment] 2021-10-07 23:11
I got a VS2022 survey and I said it was a no-go because it is missing code maid.

**Comment by NaserArab** [comment] 2021-10-12 19:01
I can't wait till this is finished, great work out there, code maid has been a MUST for me for years now .

**Comment by Plarpoon** [comment] 2021-10-14 13:47
I'm very much interested in this one, glad it is already being worked upon, thank you all!

**Comment by codecadwallader** [comment] 2021-10-14 15:20
Good news status update:

#847 was made by @olegtk to handle the `FindPattern`/`ReplacePattern` APIs not being supported in VS2022.  These weren't listed as removed APIs so I've opened this issue in the docs: https://github.com/MicrosoftDocs/visualstudio-docs/issues/7148 

There is a newer IFindService that was introduced with VS2019 which is now used instead.  This migration by @olegtk was a huge help as find/replace is a pretty core pattern and was blocking a lot of functionality.  This is a pretty significant change so some regression testing eyes would be greatly appreciated.

We'll have to drop support for VS2017 with the next release since there isn't an API that works from VS2017-VS2022.  I haven't updated the code base yet with making VS2019 the minimum required version but this will be CodeMaid v12 with VS2019+VS2022 support.

I'm also planning to drop the integration tests.  They haven't worked since pre-VS2017 (see #467 for details) and it doesn't make sense to migrate them to the new shared project structure if they won't work anyways.  It's a bummer and I'm hopeful to bring them back from the source control archives some day if they become supported again.

I'm very happy to say we've got an initial version that is available for alpha testing with VS2022 only:

[CodeMaid.VS2022.20211014T145200.vsix.zip](https://github.com/codecadwallader/codemaid/files/7347318/CodeMaid.VS2022.20211014T145200.vsix.zip)

This will have to be manually installed and uninstalled to VS2022 since it is out of band.  Some new CI/CD pipeline updates will need made since VS2019 and VS2022 will have to compile/install separately.

If you like to live dangerously and would like to help out with testing this version out it would be greatly appreciated!  As you encounter issues please spin up new GitHub issues and clearly indicate that it is for VS2022 (part of the issue template).

Thanks all for the help and enjoy!

**Comment by screaney** [comment] 2021-10-14 16:15
Just installed the Alpha on my VS2022.  The primary features I've been missing (Find in solution explorer, Reorganze and Cleanup) are all working perfectly.  This is fantastic, keep up the good work!

**Comment by pierrebrito** [comment] 2021-10-14 16:16
What a wonderful new! I was looking forward to it!
I'm a big fan of the "Ctrl+M, Space" cleanup shortcut.
I've been testing it here... and from what I can see it's not working with .**razor** files

**Comment by olegtk** [comment] 2021-10-17 07:26
@pierrebrito was it working with .razor files in VS 2019? I just tried and seems not to me.

**Comment by pierrebrito** [comment] 2021-10-17 15:35
@olegtk In 2019 it works perfectly.
In 2022 it is with this bug.

**Comment by olegtk** [comment] 2021-10-17 18:19
@pierrebrito can you please share repro steps?

**Comment by olegtk** [comment] 2021-10-18 05:26
@codecadwallader, see PR #851 addressing aforementioned issue #849.

**Comment by codecadwallader** [comment] 2021-10-21 12:51
Here is an updated build with the fix made by @olegtk in #851

[CodeMaid.VS2022.20211021T134900.vsix.zip](https://github.com/codecadwallader/codemaid/files/7389123/CodeMaid.VS2022.20211021T134900.vsix.zip)

Thanks for the regression testing so far and glad to hear it's generally working well!  Any and all testing is greatly appreciated. :)

**Comment by codecadwallader** [comment] 2021-10-30 16:55
If the testing is going well my plan is to make an official release of CodeMaid v12 with VS2022 support, ideally within the next week so it's available as VS2022 is officially launched on November 8th.

**Comment by KayakFisher205** [comment] 2021-11-02 14:12
When I install the extension to Visual Studio Version 17.0.0 RC3 and load a project it works. If I open a second copy of Visual Studio, Codemiad fails to load and in the first Visual  Studio that I loaded, CodeMaid has stopped working. I see options, but clicking doesn't open the window. Looking at the activity log for the 2nd opened Visual Studio, the error is below. I had found a page online from MS explaining about old plugin using some old pointers or soemthing, but I can't find it again at the moment. 

If I uninstall CodeMaid and close everything down, then reinstall, it works for one open Visual Studio but it crashes on the second opening.

<description>SetSite failed for package [CodeMaidPackage]Source: &apos;SteveCadwallader.CodeMaid&apos; Description: Method not found: &apos;Void EnvDTE._dispBuildEvents_OnBuildBeginEventHandler..ctor(System.Object, UIntPtr)&apos;.&#x000D;&#x000A;System.MissingMethodException: Method not found: &apos;Void EnvDTE._dispBuildEvents_OnBuildBeginEventHandler..ctor(System.Object, UIntPtr)&apos;.&#x000D;&#x000A;   at SteveCadwallader.CodeMaid.CodeMaidPackage.&lt;RegisterEventListenersAsync&gt;d__36.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at SteveCadwallader.CodeMaid.CodeMaidPackage.RegisterEventListenersAsync()&#x000D;&#x000A;   at SteveCadwallader.CodeMaid.CodeMaidPackage.&lt;InitializeAsync&gt;d__32.MoveNext() in C:\projects\codemaid\CodeMaid\CodeMaidPackage.cs:line 201&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()</description>

**Comment by codecadwallader** [comment] 2021-11-05 12:22
Thanks @KayakFisher205 for reporting the issue.  I wasn't able to reproduce it but I'm using Preview 7.0 vs RC3.  If you still see the issue as the official VS2022 comes out on Monday and the official CodeMaid VS2022 comes out by then will you please split this off as a new issue so we can dig deeper?

**Comment by codecadwallader** [comment] 2021-11-05 12:31
I've merged the `vs2022` branch to `dev` and here are a couple last beta builds if anyone wants to continue regression testing.  I'll publish over the weekend the v12.0 releases.

VS2019:
[CodeMaid.VS2019.20211105T132300.vsix.zip](https://github.com/codecadwallader/codemaid/files/7485959/CodeMaid.VS2019.20211105T132300.vsix.zip)

VS2022: 
[CodeMaid.VS2022.20211105T132300.vsix.zip](https://github.com/codecadwallader/codemaid/files/7485962/CodeMaid.VS2022.20211105T132300.vsix.zip)

Thanks everyone for the support and help! <3

**Comment by WeihanLi** [comment] 2021-11-05 14:04
> VS2022: [CodeMaid.VS2022.20211105T132300.vsix.zip](https://github.com/codecadwallader/codemaid/files/7485962/CodeMaid.VS2022.20211105T132300.vsix.zip)
> 

Works fine for me, and I'm using VS2022 Preview 7, many thanks

**Comment by screaney** [comment] 2021-11-05 15:03
If I run the .visx, should it update from the initial vs2022 release, or is it the same version? I'm just getting 'This extension is already installed to all applicable products' instead of it updating.

**Comment by Grahamvs** [comment] 2021-11-05 16:57
> 
> 
> If I run the .visx, should it update from the initial vs2022 release, or is it the same version? I'm just getting 'This extension is already installed to all applicable products' instead of it updating.

You'll need to first uninstall the previous version, then install the new version.

I'm assuming @codecadwallader didn't change the version number as this was meant to be "quick and dirty" beta build to satisfy us impatient people until he officially releases it through NuGet :)

**Comment by achilleaskar** [comment] 2021-11-07 11:30
I have a class about 5k lines and I use Ctrl +M, Ctrl+Z to reorganize it. It does reorganize it and after 3-5 seconds of lag VS22 restarts. Is there any info I can provide to you and help you find out the reason? There are many comments in the class and I also use the option to create regions that I love.

**Comment by codecadwallader** [comment] 2021-11-07 23:10
@WeihanLi thanks for confirming!

@screaney for these alpha/beta releases the build version increments are not enough for Visual Studio to distinguish between them and you'll need to manually uninstall/reinstall to use them.  However I just published the official releases so please feel free to go back to those!

@Grahamvs Correct, except it's the Visual Studio Gallery not NuGet where you can find them. :)

@achilleaskar There's definitely a known linear performance implication based on the size of the file.  See #655 for some details/workarounds.

And since we're officially live, closing this issue!  Woot and thanks again all!  If you see issues with the official releases please go ahead and open new issues as usual. :+1:

**Closed as completed by codecadwallader** 2021-11-07 23:10 UTC

**Comment by Eli-Black-Work** [comment] 2021-11-08 02:14
Yay! Thanks a ton, @codecadwallader ! ^_^

**Comment by Grahamvs** [comment] 2021-11-08 13:07
> @Grahamvs Correct, except it's the Visual Studio Gallery not NuGet where you can find them. :)

Haha @codecadwallader, you're right. You would think that I would know better since I did release my own little VS extension on the VS Gallery about 2 - 3 years ago, lol.

**Comment by scottkuhl** [comment] 2021-11-08 17:08
Just an FYI at this point, but the extension is not showing up in the marketplace.

![image](https://user-images.githubusercontent.com/4465616/140786560-46308bb1-6079-4afa-95fa-73640d1f3135.png)

![image](https://user-images.githubusercontent.com/4465616/140786590-5e9adcd4-63f1-4fe1-9b2d-f0003737ca52.png)

**Comment by codecadwallader** [comment] 2021-11-08 19:26
@scottkuhl thanks for the heads up - I think it’s fixed now if you can try again!

**Comment by craigktreasure** [comment] 2021-11-08 20:26
Looks good now. I was able to install it from the marketplace in 2022.
