### ISSUE TITLE
CodeMaid exception when used with ReSharper

### ISSUE THREAD

**Issue by BrainDedd** [codecadwallader/codemaid#62] opened 2015-01-07 07:17 UTC
I believe ReSharper hides the "organise and remove usings" command from the Visual Studio right click menu. This causes an exception in CodeMaid when it tries to call the command.
>```[CodeMaid Handled Exception 09:06:45 AM] Stopped cleaning 'ExternalDocumentController.cs': System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UsingStatementCleanupLogic.RemoveUnusedUsingStatements(TextDocument textDocument, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClassb.<Cleanup>b__9()
   at SteveCadwal0lader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)```

**Comment by codecadwallader** [comment] 2015-01-07 12:48
This is a known issue with ReSharper 9 that they have fixed in ReSharper 9.0.1.  Please grab the latest version of ReSharper and that should(tm) get things working again for you. :)

**Comment by codecadwallader** [comment] 2015-01-07 12:48
Duplicate of #43

**Closed by codecadwallader** 2015-01-07 12:48 UTC
