### ISSUE TITLE
#If Debug #endif

### ISSUE THREAD

**Issue by temonk** [codecadwallader/codemaid#887] opened 2021-12-02 11:52 UTC
Using VS 2022 and Codemaid VS2022

Settings: Cleanup Active Document and Automatic cleanup on save  both are marked 

To reproduce whenever I write #if  conditional statement with #endif Codemaid automatically removes #endif  line of the statement or  the whole #if #endif statement

Example:

 #if DEBUG 
 // Some of my code
#endif 
or 
 #if RELEASE
 // Some of my code
#endif 

Codemaid sometimes deletes #endif  statement and leaves the code uncompiled  or removes the whole
 #if #endif statement

Example after save my code becomes 

 #if DEBUG 
 // Some of my code

or it's completely deleted

**Comment by codecadwallader** [comment] 2021-12-03 13:14
Thanks for reporting the issue.  Can you please check and see if this is a duplicate of #879 ?  If it is not, can you please include a slightly longer code sample?

**Closed as completed** 2021-12-13 14:56 UTC
Labels: bug, feature: cleaning
