### ISSUE TITLE
does not insert regions for VS 2013 Update 4

### ISSUE THREAD

**Issue by mkamoski** [codecadwallader/codemaid#81] opened 2015-02-24 14:56 UTC
Please help.

CodeMaid 0.7.5 does not insert regions for VS 2013 Update 4. I run cleanup for all code. No regions are inserted. 

I have CodeMaid set as follows, 

(1). I have set >> Configuration >> Cleaning, >> Remove >> Regions >> Remove Regions >> Empty Regions = Selected. 

(2). I also have set >> Configuration >> Reorganizing >> Regions >> Insert >> Insert New Regions = Selected.  

(3). I also have set >> Configuration >> Reorganizing >> Regions >> Remove >> Remove Existing Regions = Selected.

I have tried various permutations of (1) and (2) and (3) above and none seem to work.

Here is what I want-- I want CodeMaid to handle ALL region creation and management. Put them in when they are not there and put the right things inside them. Also remove them when they are empty. Also remove any hand-made/custom regions that were not created by CodeMaid. I cannot seem to achieve this with any combination of settings. Furthermore, this used to work for me with a previous version of CodeMaid and VS 2012. 

Is this a bug? Or what is the proper combination of settings to use to get this to work?

Please advise. 

Thanks.

-- Mark Kamoski

**Comment by mkamoski** [comment] 2015-02-24 14:59
![codemaidissue201502240954 zip](https://cloud.githubusercontent.com/assets/795941/6351722/bba3cdac-bc0b-11e4-9d30-afcb20e97042.jpg)

This is actually a zip (remove the ".jpg" and unzip), which contains my project and my CM settings.

**Comment by mkamoski** [comment] 2015-02-24 15:01
Just right-click that "image" that I attached, and "save target as", and that is the zip of all the backup for the issue that I am having here. I did it this way because the github form said "attach images" and I was trying to attach a zip so I did the old "rename with a .jpg extension" as a workaround. Hope this makes sense to you. Thanks.

**Comment by codecadwallader** [comment] 2015-02-25 01:23
Makes sense, and the settings listed above sound accurate to me.  Taking a look.

**Comment by codecadwallader** [comment] 2015-02-25 01:44
I've been unable to reproduce the issue using the settings and solution you sent to me, but I think I know what's the problem.  Regions are only inserted/removed when reorganization runs, not when cleanup runs.  If you want to "chain" reorganization to run when cleanup all code is executed, then you'll need to turn on the CodeMaid option at Reorganization->General->"Run reorganize at start of cleanup".  This option is off by default, but one you had probably enabled in VS2012.

If it's any consolation, in the next major release we're going to have shared settings across Visual Studio versions.  So it likely wouldn't happen again on the VS2013->VS2015 upgrade.

I'm closing the issue assuming that is the problem, but if not please comment and we'll re-open to investigate further.

**Closed by codecadwallader** 2015-02-25 01:44 UTC
