### ISSUE TITLE
Making a new line between different using libraries to separate them

### ISSUE THREAD

**Issue by FinalHeaven** [codecadwallader/codemaid#316] opened 2016-07-26 03:32 UTC
### Environment
- Visual Studio version: 2015 Community
- CodeMaid version: 10.1
- Code language: C#

### Description
add new line for different libs:
using System.Web;
using System.Data;

using Helperslib.Code;
using Helperslib.format;

using DataHelp.AdoCode;
using DataHelp.TranactionCode;

**Comment by codecadwallader** [comment] 2016-07-26 15:26
Thanks for the suggestion.  I believe this is a duplicate of #151 if you would like to vote up/watch that issue.

**Closed by codecadwallader** 2016-07-26 15:26 UTC
