### ISSUE TITLE
Null Reference Exception when starting VS with CodeMaid enabled

### ISSUE THREAD

**Issue by JamesEvolution** [codecadwallader/codemaid#664] opened 2019-07-22 08:25 UTC
### Environment
- Visual Studio version: 2019 Pro
- CodeMaid version: 11.0
- Code language: C#

### Description
Visual Studio throws a Null Reference Exception shortly after starting when CodeMaid is enabled.
![image](https://user-images.githubusercontent.com/33928277/61617074-e842ae00-ac61-11e9-8c72-6016fcfcfa71.png)

### Steps to recreate
1. Start VS
2. Open a solution 
3. Wait for a few seconds
4. BAM!

This behaviour doesn't occur with CodeMaid disabled.

Relevant entries from the VS Activity Log (from the Open Log button on the error banner):

```xml
  <entry>
    <record>2113</record>
    <time>2019/07/22 08:16:47.895</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Razor.RazorCodeGenerator.DocumentParseCompleteMainThread()&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Razor.RazorCodeGenerator.&lt;DocumentParseComplete&gt;b__45_0()&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
  <entry>
    <record>2114</record>
    <time>2019/07/22 08:17:51.968</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Performance warning: String load failed. Pkg:{1B027A40-8F43-11D0-8D11-00A0C91BC942} LANG:0409 ID:1301&#x000D;&#x000A;</description>
  </entry>
```

**Comment by codecadwallader** [comment] 2019-07-23 12:10
Thanks for reporting the issue.  I believe this is a duplicate of #653 which has some more information

**Closed by codecadwallader** 2019-07-23 12:10 UTC
Labels: duplicate
