### ISSUE TITLE
Automatic cleanup on save crashes Visual Studio 2015 when performing a 'Rename'

### ISSUE THREAD

**Issue by BrettMStory** [codecadwallader/codemaid#153] opened 2015-09-09 14:52 UTC
With CodeMaid in Visual Studio 2015, enable automatic cleanup on save and do a rename factor (I've specifically seen it with local variables, fields, and properties, but I assume it will occur regardless). It appears to crash Visual Studio every time. If I disable the CodeMaid plugin or turn off automatic cleanup, then nothing breaks. I imagine the trouble comes in when Visual Studio does an automatic save upon doing a rename refactor. Should be reproducible, happens to everyone on my team 100% of the time.

I am using CodeMaid v 0.8.1 and Visual Studio 2015 (v 14.0.23107.0).

**Comment by codecadwallader** [comment] 2015-09-09 15:08
Please take a look at #142 as this sounds very familiar. If that doesn't resolve your issue, can you please reopen this with a copy of your settings.

**Comment by BrettMStory** [comment] 2015-09-09 15:55
We still saw the issue after changing those three settings. Here's a [gist with our settings](https://gist.github.com/BrettMStory/3878e6bcc90717c411e0).

**Comment by codecadwallader** [comment] 2015-09-11 00:08
Thank you for providing your settings.  I've been able to reproduce the issue, and isolate it to the Reorganizing-Remove Existing Regions logic.  It is getting into an infinite loop with the undo transaction context in VS.  Investigating..

**Comment by codecadwallader** [comment] 2015-09-11 00:09
Quick workaround: if the option to remove existing regions within reorganization is disabled that error does not occur.

**Comment by codecadwallader** [comment] 2015-09-11 00:16
For Cleaning and Reorganization logic, we explicitly avoid the undo transaction logic during automatic cleanup on save because of the potential to loop.  The remove existing regions logic is using shared code (you can also directly invoke through context menus) that invokes the undo transaction logic but does not include that guard.

**Comment by BrettMStory** [comment] 2015-09-11 12:06
Thanks, the workaround is working for us. We don't really use regions, so its not a big loss for us to turn off that feature. Good luck on fixing the issue and thank you for all of the help you provided.

**Comment by codecadwallader** [comment] 2015-09-11 12:31
Cool, glad to hear it isn't blocking you.  Thanks again for reporting the issue and it will be resolved in the next release.

**Comment by codecadwallader** [comment] 2015-09-27 11:51
Changes made to address this issue, will be present in the next release.

**Comment by codecadwallader** [comment] 2015-11-01 18:33
This is present in the latest release, https://github.com/codecadwallader/codemaid/releases/tag/v0.8.8-alpha.  If you have the chance to test it and comment that would be greatly appreciated!

**Closed by codecadwallader** 2015-11-01 18:33 UTC
Labels: reproduced, resolved

**Comment by BrettMStory** [comment] 2016-01-15 14:35
I apologize for taking so long to comment, but my team has been using the latest release for a while and we have not seen this issue. Thanks for responding so quickly and fixing it!

**Comment by codecadwallader** [comment] 2016-01-15 18:31
No worries, glad to hear it's resolved - thanks again for helping to find it. :)

**Comment by Andy65** [comment] 2016-04-25 09:41
I am experiencing this issue with VS 2015 Update 2 and CodeMaid 10.1 and as originally reported, disabling the cleanup on save solves the problem of VS crashing.  Your suggested workaround of switching of the Remove Regions also solves the problem.

**Comment by codecadwallader** [comment] 2016-04-25 11:34
Have you also checked the setting referenced in #223 for undo transactions?  If that doesn't resolve the issue, can you please provide an export of your user and solution-specific settings?

**Comment by Andy65** [comment] 2016-04-25 11:54
I have checked and both Use undo transactions and Skip during automatic cleanup on save are selected. I am not currently using solution-specific settings so have only included an export of my user settings
[CodeMaid.zip](https://github.com/codecadwallader/codemaid/files/234445/CodeMaid.zip)

**Comment by codecadwallader** [comment] 2016-04-25 14:33
It looks like the option for removing unused using statements, "skip during automatic cleanup on save" has been disabled.  If you re-enable this option, does the hang go away?

The primary reason for all of the "Skip during automatic cleanup on save" is specifically for infinite loops that can happen between refactor->save->cleanup->refactor chains.  In particular certain commands like remove unused using statements can trigger additional events that propagate the chain of events.

**Comment by Andy65** [comment] 2016-04-25 14:42
It is not a hang, it is a crash and yes, re-enabling the 'skip during automatic cleanup on save' does make the problem go away. Is there not a better way of dealing with the cascade of events rather than having users having to set options in configuration?  Perhaps setting a flag on the first event and ignoring subsequent events until the flag has been cleared (easy to say of course :)).

**Comment by codecadwallader** [comment] 2016-04-25 15:45
I think it's usually an infinite loop hang until the call stack is exhausted, which yeah will lead to a crash.  Regardless of how it surfaces, it isn't good. ;)

That option is enabled by default (safe approach) so it does require a user to go disable that option as well as using the VS refactoring commands.  I've considered stripping away the option to skip it at all since it can lead to issues in some circumstances, but I usually get push back from users that they want the power to choose for themselves if an option is a good fit for not.  For example people using ReSharper refactoring commands want that ability to customize the behavior since they won't encounter the same loop as VS refactoring causes.

It's a tricky situation that I'm struggling with to be honest.  Everybody likes to have more options so they can tailor the tool for their scenario, but I can't test nor guarantee all option combinations work for all scenarios.  A brush-off solution is to put a 'danger' icon next to that option.. but that argument could be made for many options (e.g. automatic cleanup on save will affect files _on every save_).  As an open source project, I'm absolutely open to ideas, conversations, etc. to find the right balance between power and safety with options.

Sorry for the long winded spiel.  It's a topic I've been thinking about a lot recently as we frequently find issues reported can be traced back to power settings that have let people shoot themselves in the foot.  Again, ideas welcome and maybe it's good fodder for a new issue for public discussion!
