### ISSUE TITLE
Issue when saving a C# file that has an empty comment

### ISSUE THREAD

**Issue by ChristineBoersen** [codecadwallader/codemaid#214] opened 2016-02-12 00:20 UTC
Given that I am a user,
When saving a C# file and Automatic Cleanup set to on and the file contains an empty single line comment (//)
Then the code needs to check for nulls properly as the following error is produced.

[CodeMaid Handled Exception 07:14:57 PM] Stopped cleaning 'DocumentClassificationGridController.cs': System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Matches(String input)
   at SteveCadwallader.CodeMaid.Model.Comments.CommentFormatter.Parse(ICommentLine line, Int32 indentLevel, Int32 xmlTagLength)
   at SteveCadwallader.CodeMaid.Model.Comments.CommentFormatter..ctor(ICommentLine line, String commentPrefix, Int32 tabSize, Regex regex)
   at SteveCadwallader.CodeMaid.Model.Comments.CodeComment.Format()
   at SteveCadwallader.CodeMaid.Logic.Formatting.CommentFormatLogic.FormatComments(TextDocument textDocument, EditPoint start, EditPoint end)
   at SteveCadwallader.CodeMaid.Logic.Formatting.CommentFormatLogic.FormatComments(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment] 2016-02-12 01:32
Thanks for reporting the issue.  I tried to reproduce it but so far have been unsuccessful.  I attempted to reproduce it by having single line comments with `//`, files that were completely empty except for single line comments with `//`, as well as multi-line comments with single lines within them that had `//` but none of those seemed to trip the error condition you mentioned.

Some information that would be helpful:

- Visual Studio version
- CodeMaid version
- CodeMaid configuration (exportable through Options)
- Sample code file

**Comment by ChristineBoersen** [comment] 2016-02-12 01:37
Microsoft Visual Studio Professional 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-50050-03651-AA481
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-50050-03651-AA481
Microsoft Visual Basic 2015

Visual C# 2015   00322-50050-03651-AA481
Microsoft Visual C# 2015

Visual C++ 2015   00322-50050-03651-AA481
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-50050-03651-AA481
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   4.2.60128.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.2   14.0.20115.0
Azure App Service Tools v2.8.2

Bundler & Minifier   1.8.144
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project

CodeMaid   v0.9.0
CodeMaid is an open source Visual Studio extension to cleanup, dig through and simplify our C#, C++, F#, VB, PHP, PowerShell, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Written by Steve Cadwallader, for more information visit http://www.codemaid.net/

Color Theme Designer   1.0
Designer for creating new color themes

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Google Chrome Project Template   1.0
Information about my package

Indent Guides   14
Indent Guides

Adds visual guides at each indentation level.

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.0.163
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.31124.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.31124.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.31124.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Telerik ASP.NET MVC VSExtensions   2016.1.111.0
Telerik UI for ASP.NET MVC VSExtensions

Telerik DataAccess VSExtensions   2015.5.1030.0
Telerik DataAccess VSExtensions

TypeScript   1.7.6.0
TypeScript for Microsoft Visual Studio

Visual Studio Tools for Unity   2.1.0.0
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

WakaTime   1.0


Web Compiler   1.10.302
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015   1.0.204
Adds many useful features to Visual Studio for web developers.

Xamarin   4.0.0.1717 (1390b70)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.0.35 (d300845)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.3.99.33 (ea30b32)
Visual Studio extension to enable development for Xamarin.iOS.

[CodeMaid.zip](https://github.com/codecadwallader/codemaid/files/127381/CodeMaid.zip)

**Comment by codecadwallader** [comment] 2016-02-12 13:48
Thanks for the additional details, I have now reproduced the issue.

It only appears to happen when both _automatic cleanup on save_ and _run format comments during cleanup_ are enabled.  If you manually invoke a comment format on that line it will recognize that it is not something that can be meaningfully formatted and prevent getting to the Parse routine.

@willemduncan I think this could be a pretty straight-forward guard for scenarios where there's an empty comment.  In particular the call stack shown above is for https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Model/Comments/CommentFormatter.cs#L173 and `line.Content` will be null.  Thoughts?

**Comment by ChristineBoersen** [comment] 2016-02-12 18:01
No problem. Glad I could help.

**Comment by willemduncan** [comment] 2016-02-28 09:13
I was a bit worried when I read that the crash happens on auto cleanup but not during manual formatting, since it runs exactly the same code. I'm glad to report that both versions crash, only the manually invoked action swallows the exception in the undo helper and does not display it.

**Comment by codecadwallader** [comment] 2016-02-28 20:57
@willemduncan That's a good point.  The try/catch/finally within the Run statement is to make sure we don't put the IDE undo context into a bad state, but perhaps we should do some default diagnostics logging as well.  The only two places that do provide a catch action (cleaning, reorganizing) write diagnostics to the output window and update the VS status bar.  I'm not sure if that's a fit for every command that uses it, but probably several of them.. thoughts?

**Comment by willemduncan** [comment] 2016-02-29 08:10
Since you *can* provide an optional error handler, maybe just use a default if none is given explicitly. The document-wide "Cleanup" command has a nice error handler: [CodeCleanupManager.cs](https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/CodeCleanupManager.cs#L192).

I would write a short diagnostic message on every unhandled exception. It does not require a full stack trace on a release build, but an indication that something went wrong so people can report problems easier.

**Comment by codecadwallader** [comment] 2016-02-29 14:02
Cool, thanks for the input - I'll plan on doing that.

**Comment by codecadwallader** [comment] 2016-03-03 12:24
@willemduncan Thanks again for the suggestion, UndoTransactionHelper logging improvements now merged in.  Thoughts on the right place for a null content check for the original issue?

**Comment by willemduncan** [comment] 2016-03-08 09:21
I'd say it depends a bit on what you do with the `Action<Exception> catchAction = null`. Right now you you will write all exceptions to the output window, regardless of the catch action. If there are any situations in which you deal with the exception inside the handler, you probably don't want to output it as well.

If you change the argument (or create an overload, so you do not break existing code) that takes a `Func<Exception, bool> catchAction`, you could then allow the catch action to decide whether to write to the output window or not. Of course, this only makes sense if you actually have catch actions that "override" the exception.

**Comment by codecadwallader** [comment] 2016-03-08 12:19
Yep, agreed.  There's actually no implementations of the catchAction any more since the default behavior was based on what the cleanup and reorganization methods were using.  I left it in place as an easy extension point going forwards, although normally I would remove it since it's not currently being utilized.

**Comment by codecadwallader** [comment] 2016-03-17 01:51
As v0.9.1 is now released, closing this issue.

**Closed by codecadwallader** 2016-03-17 01:51 UTC
Labels: reproduced, resolved
