### ISSUE TITLE
Find In Solution Explorer throws error if Track Active Item is enabled

### ISSUE THREAD

**Issue by wouterroos** [codecadwallader/codemaid#290] opened 2016-05-10 10:44 UTC
### Environment
- Visual Studio version: 2015 Enterprise Update 2
- CodeMaid version: 10.1.93
- Code language: C#
### Description

When selecting the Find In Solution Explorer command in the right-click menu of a Code Editor window, the following error is thrown: 

![image](https://cloud.githubusercontent.com/assets/5137829/15143885/51227c06-16ac-11e6-8ed7-cce3e02aa4e5.png)
### Steps to recreate
1. Install Update 2
2. Open Code Editor window
3. Right-click the window tab
4. Click on Find In Solution Explorer
### Current behavior

Above error message is shown.
### Expected behavior

File is found in Solution Explorer.

**Comment by codecadwallader** [comment] 2016-05-10 13:01
Thanks for reporting the issue.  This command used to be a custom implementation, but became a pass-through invocation to a now native capability of VS.  We do have a little remaining logic that makes the command more robust than native.  Can you please try the following?

1. Launch the Command Window (Ctrl+Alt+A)
2. Type SolutionExplorer.SyncWithActiveDocument

alternatively you can click the "Sync with Active Document" button in the solution explorer toolbar (two arrows pointing in opposite directions).

**Comment by wouterroos** [comment] 2016-05-11 06:23
Thanks for the feedback. After doing some testing, it seems the issue only occurs when Tools > Options > Projects and Solutions > General > Track Active items in Solution Explorer is enabled. Maybe you could consider hiding the Find In Solution Explorer menu item when this option is enabled to prevent the error?

**Comment by codecadwallader** [comment] 2016-05-11 12:31
Aha, thanks for the clarification.  I have reproduced the issue as well now when that setting is enabled and that makes sense.

In this scenario, perhaps if the command is invoked we could just activate the solution explorer window?  The net behavior then would be the same between both modes, the solution explorer has focus and the current document is highlighted.  Thoughts?

**Comment by wouterroos** [comment] 2016-05-11 13:36
Good suggestion!

**Comment by codecadwallader** [comment] 2016-05-11 13:57
Cool, we'll plan on that.  Thanks!

**Comment by codecadwallader** [comment] 2016-05-14 10:43
I've made a change that I believe will handle this scenario.  If you would like to test it out a build will be available in our [CI channel](http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/) shortly (v10.1.99 or higher).

**Comment by wouterroos** [comment] 2016-05-17 12:40
I just tested the v10.199 build and I don't get the error any more when I click Find in Solution Explorer. The only issue remaining is that, when the solution explorer gains focussed, it does not highligth the correct file (in my current solution it switches to a folder called Solution Items).

**Comment by codecadwallader** [comment] 2016-05-17 12:55
Thanks for confirming the error is no longer seen.

Since you're using the native document tracking, that replaces the logic that would normally highlight the correct file.  We are now only invoking the solution explorer when tracking is enabled because the command that finds the correct item cannot be used while tracking is active.  FWIW I have noticed that behavior if you have a document open that is not a part of the solution.

**Comment by codecadwallader** [comment] 2016-12-11 12:29
Marking this as closed as we prepare for a next release.

**Closed by codecadwallader** 2016-12-11 12:29 UTC
Labels: bug, reproduced, resolved
