### ISSUE TITLE
Unwanted insertion of duplicate using statement

### ISSUE THREAD

**Issue by lellid** [codecadwallader/codemaid#501] opened 2017-11-15 20:48 UTC
### Environment
- Visual Studio version: 15.4.3 Community
- CodeMaid version: 10.4
- Code language: C#

### Description
If the using statements in a file are not in alphabetical order, a duplicate using statement is inserted two lines after the last original using statement.

### Steps to recreate
1. Create Test2.cs (this file is solely to create the namespace Altaxo):
```
namespace Altaxo
{
	public class Test2
	{
	}
}
```

2. Create Test1.cs (which will be later cleaned up by CodeMaid):
```
using System;
using Altaxo;

namespace Foo
{
	internal static class Test1
	{
		private static void Test()
		{
			var a = new Test2(); // reference to namespace Altaxo ...
			var b = new Tuple<int, double>(1, 1); // reference to namespace System ...
		}
	}
}
```

3. Cleanup Test1.cs by choosing CodeMaid->Cleanup Active Document from the context menu
My settings are:
- Run Format document: Checked
- Run Remove and sort using statements: Checked
- Skip during automatic cleanup on save: Checked
- using statements to re-insert when removed:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
```

Current behavior: This will result in the following code:
--------------------------------------------------------------
```
using System;
using Altaxo;

using System;

namespace Foo
{
	internal static class Test1
	{
		private static void Test()
		{
			var a = new Test2(); // reference to namespace Altaxo ...
			var b = new Tuple<int, double>(1, 1); // reference to namespace System ...
		}
	}
}
```

Expected behavior:
--------------------

The using statements should be ordered alphabetically. The duplicate insertion of the ``using System;`` statement should be avoided.

**Comment by codecadwallader** [comment] 2017-11-16 11:38
Thank you for reporting the issue.  I believe this is a duplicate of #390

**Closed by codecadwallader** 2017-11-16 11:38 UTC
