### ISSUE TITLE
The Command to execute is not enabled.

### ISSUE THREAD

**Issue by TreborEcurb** [codecadwallader/codemaid#139] opened 2015-08-11 22:36 UTC
I'm using VS Premium 2013, Update 5 and CodeMaid v 0.8.0 working on a c# solution.  Selecting the "Find In Solution Explorer" results in the exception message, "The Command to execute is not enabled."  How do I enable the Command?
Some background: The solution contains 4 projects.  The sought document was in a different project than the one in which it was referenced, but the same solution.
![solutionstruct](https://cloud.githubusercontent.com/assets/13755859/9212509/0d688b7e-404f-11e5-93ce-8e6245e93809.JPG)
Specifically, I was working on a control and sought the location of a "Def" document.

**Comment by codecadwallader** [comment] 2015-08-12 11:00
Thanks for the details.  The only requirement for that command to be enabled is that there is an active document (i.e. an open file).  At the moment I'm unable to reproduce it, but here are a couple things to try:

1)  Does the command appear disabled in all three locations
  1a) CodeMaid menu
  1b) Right-click on document tab name
  1c) Right-click inside document window
2)  If you double click on a file from the solution explorer to open it, then right click inside the document window to find the file, is the command still disabled?
3)  Upgrade to the latest CodeMaid v0.8.1.  There aren't any direct changes for the finding functionality, but it's a good way to force a reinstall.
4)  Enable CodeMaid->Options->Diagnostics mode, and look at the details being provided in the Output tool window.  This should affirm that CodeMaid is building code models and taking other actions that are also dependent on an open file.

Hopefully one of those approaches will give us a clue as to what may be going on.

**Comment by codecadwallader** [comment] 2015-08-12 11:23
On further thought, are you saying that the CodeMaid command is enabled, but when you run it you are getting an exception message about the command not being enabled?

If so, CodeMaid internally invokes a native Visual Studio command to run this operation.  One more thing to try:

5) Go to the Command Window and run "SolutionExplorer.SyncWithActiveDocument".  This is effectively all that CodeMaid is doing in VS2012 and higher since it became a native capability.

If that command will not run, it is possible another extension (e.g. ReSharper 9.2 EAP) has disabled it.

**Comment by TreborEcurb** [comment] 2015-08-12 15:26
You are correct; the CodeMaid command is enabled in all three places.  I've upgraded to v0.8.1 and there are no visible changes in this particular function.  When I execute the "SolutionExplorer.SyncWithActiveDocument" command, the results are: Command "SolutionExplorer.SyncWithActiveDocument" is not available.

The output from the Diagnostics mode test are:
[CodeMaid Diagnostic 10:23:30 AM] WindowEventListener.OnWindowChange raised for 'P:\Projects\Core\CoreControls\ManageAirports2\Controls\Handlers\HandlersMainControl.cs'
[CodeMaid Diagnostic 10:23:35 AM] FindInSolutionExplorerCommand.OnExecute invoked
[CodeMaid Diagnostic 10:23:35 AM] FindInSolutionExplorerCommand.ToggleSolutionFoldersOpenTemporarily expanding 'Solution Items'
[CodeMaid Diagnostic 10:23:35 AM] FindInSolutionExplorerCommand.ToggleSolutionFoldersOpenTemporarily collapsing 'Solution Items'

I am using Infragistics v13.2.  Would this inhibit the "Find In Solution Explorer" command?

**Comment by codecadwallader** [comment] 2015-08-13 11:58
I'm not sure if Infragistics would be causing a conflict, you could try disabling it to see.  I wouldn't think so as from my memory they're a control provider vs. doing deep VS integration, but it's been a few years since I've used that product.

That command is visible in the Solution Explorer toolbar as two arrows pointing in opposite directions.  It may be worthwhile to keep an eye on that and see if there's ever any conditions where it does become enabled (e.g. certain project/file types).

**Comment by codecadwallader** [comment] 2015-09-23 11:28
Closing due to inactivity.  Please comment to reopen.

**Comment by itsmeks** [comment] 2015-11-18 16:21
Hi,
I am getting the same issue. Command is enables on all places. but when I click I get error. 

---------------------------
Microsoft Visual Studio
---------------------------
The Command to execute is not enabled.
---------------------------
OK   
---------------------------

I have enabled the diagnosis. Following is shown in output window. I am on the latest version of CodeMaid and Vs 2013 Update 5.

[CodeMaid Diagnostic 09:19:54 PM] WindowEventListener.OnWindowChange raised for 'D:\XFSEL\XFS.Model\Faq.cs'
[CodeMaid Diagnostic 09:19:57 PM] FindInSolutionExplorerCommand.OnExecute invoked

**Comment by codecadwallader** [comment] 2015-11-19 01:09
Ok, can you please try all of the suggestions in comments above - particularly https://github.com/codecadwallader/codemaid/issues/139#issuecomment-130265042 and https://github.com/codecadwallader/codemaid/issues/139#issuecomment-130640927

**Comment by itskhurram** [comment] 2015-11-19 13:02
I got following error when try to run command.
'SolutionExplorer.SyncWithActiveDocument' is not recognized as an internal or external command,
operable program or batch file.

and Yes "<>" is always visible in solution exploror tool bar.

**Comment by codecadwallader** [comment] 2015-11-19 13:43
If you go to the command window, it has IntelliSense to try and auto complete.  After you type "SolutionExplorer.", what options do you see?  Also, it would be helpful to know what type of project you are using (C#, VB, etc.) in case that is a factor.

**Comment by itskhurram** [comment] 2015-11-19 14:02
I am working on C# project.
I can see attached options.
Following error is shown when i run command.
>SolutionExplorer.SyncWithActiveDocument
Command "SolutionExplorer.SyncWithActiveDocument" is not available.
![solution](https://cloud.githubusercontent.com/assets/5083361/11272633/19a7dc1a-8ef0-11e5-936f-ef4d3a09f153.png)

**Comment by itskhurram** [comment] 2015-11-19 17:05
Interestingly i installed following extension and its working fine.

Find in Solution Explorer
https://visualstudiogallery.msdn.microsoft.com/d2fc1e94-b85c-4a15-8569-390db1e04f47

**Comment by codecadwallader** [comment] 2015-11-21 11:49
@itskhurram That's strange, as it looks like it is also just a wrapper around the Visual Studio SyncWithActiveDocument command too - same as CodeMaid.

I'm not sure if there's anything remaining to do here, so closing the issue for now but if anybody still needs help please just comment.

**Closed by codecadwallader** 2015-11-21 11:49 UTC
Labels: not reproduced
