### ISSUE TITLE
Custom XML tags gets incorrectly formatted.

### ISSUE THREAD

**Issue by ameyasubhedar** [codecadwallader/codemaid#113] opened 2015-07-03 13:17 UTC
Thanks for the wonderful tool. Recently we have started using this tool and overall works great !

Issue Description:
Our code standard enforces addition of name, date and reference to every comment. We use custom tags for writing code comments so that they can be extracted out later by code parser to build code/feature ownership depository and to know who changed a piece of code and why.

![image](https://cloud.githubusercontent.com/assets/13166236/8499633/71a8b462-21b2-11e5-8d49-5eacd75e7065.png)

After I run clean up all these tags gets formatted to new line. This is not expected as it not used in the context of an XML documentation tag.

![image](https://cloud.githubusercontent.com/assets/13166236/8499689/ecfb69ac-21b2-11e5-9b71-209e5a054607.png)

Any workaround to avoid moving these tags to new line during clean up. I have tried various setting but same result ?

![image](https://cloud.githubusercontent.com/assets/13166236/8499776/c7779286-21b3-11e5-92a8-d28fcc46cb83.png)

**Comment by codecadwallader** [comment] 2015-07-03 18:21
You're welcome, we're glad you're enjoying it. :)

Have you tried the "Keep XML tags together" option?  I'm going from memory but I thought that one would stop new lines from being added between XML tags.

**Comment by ameyasubhedar** [comment] 2015-07-04 08:43
Thanks for responding.

Yes, I have tried  "Keep XML tags together", and the issue is reproducible.

**Comment by codecadwallader** [comment] 2015-07-08 11:32
I'm able to reproduce the issue as well, and walking through the code I don't currently see a configuration option to prevent those new lines.

@willemduncan When you have some time, can you please take a look at this issue and provide your thoughts?  I thought the "Keep XML tags together" option would do it but I think it just ensures opening/closing tags for an individual tag don't get placed on a separate line from their content.  Looking in CommentFormatter it looks like we explicitly new line between every XML tag currently.  https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Model/Comments/CommentFormatter.cs#L83

**Comment by willemduncan** [comment] 2015-07-08 11:46
the "Keep Together" option ensures that a tag with attributes is not split across multiple lines, ie. that it does not split on the space between tag and attribute. Not relevant here.

A workaround for now is to add a blank non-comment line between the XML and actual comment part, so you can format them independently.

The formatter does indeed force root level XML tags to their own line. XML is not expected in 'normal' comments. I'm thinking maybe we should start being a bit more strict and only parse triple slash `///` comments as XML, and format double slash `//` as regular text.

**Comment by codecadwallader** [comment] 2015-07-08 11:58
Thanks for the details.  You're right about it being specific to root level tags, I found that adding a root 'doc' tag wrapper is a workaround:
```xml
// <doc><author>Author1</author><reference>ProjectID</reference><date>Tue Jun 23 2015</date></doc>
// Test Issue 113
```

Makes sense on adding more distinction between XML/normal comments, although I'm not sure if there's other use cases that would stop that currently work.

**Comment by ameyasubhedar** [comment] 2015-07-11 09:27
Thanks... the workaround works well for us. Let me know if you would like me to close the issue.

**Comment by codecadwallader** [comment] 2015-07-11 10:31
I'm glad to hear it, thanks for following up.  Closing the issue.

**Closed by codecadwallader** 2015-07-11 10:31 UTC
Labels: reproduced
