### ISSUE TITLE
Clean on Save always leaves the file marked as dirty

### ISSUE THREAD

**Issue by StuartHemming** [codecadwallader/codemaid#88] opened 2015-03-31 07:04 UTC
I have Codemaid installed along with JustCode. With all of the default settings in Codemaid in place and with Clean on Save enabled saving a file cleans and saves the file and then marks it as dirty again so it needs saving again. Repeatedly saving the file without making any changes always leave the file marked as dirty.

I'm running:
- VS 2012 (v11.0.61030.00 update 4)
- JustCode Q1 2015 SP1 (internal)
- Codemaid v0.7.6

I have since noticed that if I disable _all_ of the Codemaid cleaning options with the exception of Clean on Save the the file is saved and JustCode _then_ cleans it (potentially marking it as dirty) but subsequently saving the file leaves it alone.

I _believe_ that the issue may be related to the fact that JustCode is set to order the using statements with the System* namespaces first whereas Codemaid seems to put them in alpha order.

**Comment by StuartHemming** [comment] 2015-03-31 08:14
I've noticed also that despite the above, .cshtml files are _always_ marked as dirty after saving.

**Comment by codecadwallader** [comment] 2015-03-31 11:23
Thanks for all of the details, that really helps.

In regards to using statements, Microsoft changed their default preference in VS2012 as they started introducing "Windows." assemblies.  The new default as of VS2012 is to place them all in alphabetical order.

You can configure this setting within Visual Studio at Tools->Options->Text Editor->C#->Advanced->"Place 'System' directives first when sorting usings".  CodeMaid respects the Visual Studio defined preference which defaults to not putting System directives first.  It sounds like JustCode may have its own option or always be following the previous standard.

In regards to .cshtml files always being marked as dirty, can you provide some sample code that exhibits the issue?  I'm not able to reproduce it with the default configuration, but I am on a VS2013 machine at the moment.  Something that would also be helpful to try is to run Edit->Advanced->Format Document to see if that also causes the file to repeatedly be marked as dirty independent of CodeMaid.

**Comment by StuartHemming** [comment] 2015-03-31 14:03
More on this.

The problem with .cshtml files appears only if there are calls to C# methods and these methods are called using dot notation...

````csharp
  if (Model.AllClassificationsAssignedToRecord.Count(c => c.ClassificationId == idToCompare) > 0)
````

I think that the problem is related to the fact that JustCode makes a mess of this  turning it in to this...

````csharp
  if (Model.AllClassificationsAssignedToRecord
           .Count(c => c.ClassificationId == idToCompare) > 0)
````

Of course, this could be a red herring.

**Comment by codecadwallader** [comment] 2015-04-01 12:30
If I add a simple line of code
`@if (Model.AllClassificationsAssignedToRecord.Count() > 0) { }`

or if I manually wrap that onto multiple lines

    @if (Model.AllClassificationsAssignedToRecord
        .Count() > 0)
    {

    }

I'm not seeing that behavior with CodeMaid alone in either scenario.

**Comment by codecadwallader** [comment] 2015-06-27 17:49
Closing due to inactivity.

**Closed by codecadwallader** 2015-06-27 17:49 UTC
Labels: not-reproduced
