### ISSUE TITLE
VS 2015 Crashes During Project Load

### ISSUE THREAD

**Issue by THammond9** [codecadwallader/codemaid#287] opened 2016-05-05 10:08 UTC
### Environment
- Visual Studio version: 2015 Professional Update 2
- CodeMaid version: 10.1.93
- Code language: C#
- Extensions: Although I have several installed they do not seem to affect this issue.

### Description
When CodeMaid is enabled Visual Studio crashes when I try to load any solution. I ruled out all extensions that I have installed by deleting all extensions except for CodeMaid in the experimental instance of visual studio and then try to load several different solutions (big, small, micro) and all of them crashed as well. The crash is about 10 seconds into loading the solution.

[ActivityLog.xml.txt](https://github.com/codecadwallader/codemaid/files/250220/ActivityLog.xml.txt)

Here is the information from the event log:

Log Name: Application
Source: .NET Runtime
Event ID: 1026
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 31686FC0
Stack:

_________________________
Log Name: Application
Source: Application Error
Event ID: 1000
Faulting application name: devenv.exe, version: 14.0.25123.0, time stamp: 0x56f22f32
Faulting module name: msenv.dll, version: 14.0.25123.0, time stamp: 0x56f22f38
Exception code: 0xc0000005
Fault offset: 0x00536fc0
Faulting process id: 0x2c64
Faulting application start time: 0x01d1a6b3e9802dc8
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\msenv.dll
Report Id: 2e80b2a8-12a7-11e6-a561-a64068fa5280

### Steps to recreate
For me:
1. Start Visual Studio
2. Open an existing project
3. Wait for 10 seconds
4. VS crashes

### Current behavior
Visual Studio crashes during project load

**Comment by codecadwallader** [comment] 2016-05-05 12:06
Thanks for reporting the issue, but I have been unable to reproduce it.  This is a very common use case scenario so I suspect it is something specific to your environment.

Taking a look at the error log it looks like there are a large number of "Unexpected system error mode before loading package X" where X is a lot of common VS modules (e.g. [CSharpPackage], [Visual Studio Project Persistence Package], etc.)

If you uninstall CodeMaid, and look at the ActivityLog after loading Visual Studio.. are those error messages still appearing?  If so you may want to run a Repair on your VS installation.

**Comment by THammond9** [comment] 2016-05-16 18:31
After posting this I got a new PC and was able to install CodeMaid. Don't really know what the issue was.

**Comment by codecadwallader** [comment] 2016-05-16 18:33
Strange, but thanks for confirming.  Will close the issue.

**Closed by codecadwallader** 2016-05-16 18:33 UTC
Labels: bug, needs detail, not reproduced
